// Public configuration only. API and Turnstile secrets belong to Cloudflare.
const AI_ENDPOINT='https://norte-gemini.joaovitorgoncalvesdev.workers.dev/ai';
const AI_SITEKEY='0x4AAAAAAFRsSVvCJLFjoSbn';
let aiMode='explain',aiContent='',aiResult=null,aiError='',aiBusy=false,aiController=null,aiWidget=null,aiToken='',aiExamId=null;
const aiModes=[['explain','Entender uma dificuldade'],['cards','Criar cartões'],['quiz','Praticar questões']];
const norbitMark='<svg viewBox="0 0 32 32" fill="none" aria-hidden="true"><path d="M8 23V9l16 14V9" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/><ellipse cx="16" cy="16" rx="14" ry="7" transform="rotate(-35 16 16)" stroke="currentColor" stroke-width="1.2" opacity=".5"/></svg>';
let aiSubmittedContent='';
function viewAI(){
 const configured=AI_ENDPOINT.startsWith('https://')&&!AI_SITEKEY.startsWith('__');
 const active=aiBusy||aiResult||aiError;
 return '<div class="norbit-page'+(active?' has-answer':'')+'"><header class="norbit-header"><div class="norbit-identity"><span class="norbit-symbol">'+norbitMark+'</span><span><strong>NORBIT <span>AI</span></strong><small>Seu parceiro de estudos</small></span></div>'+btn('Nova conversa','ai-new','','quiet small')+'</header>'+
 (active?'<h1 class="norbit-sr">Conversa com NORBIT AI</h1><div class="norbit-thread"><div class="norbit-user"><span class="norbit-message-label">Você · '+esc(aiModes.find(m=>m[0]===aiMode)?.[1]||'Estudar')+'</span><p>'+esc(aiSubmittedContent||aiContent)+'</p></div><section class="ai-output norbit-answer" aria-label="Resposta da NORBIT AI" aria-busy="'+aiBusy+'" tabindex="-1"><div class="norbit-answer-byline"><span class="norbit-symbol">'+norbitMark+'</span><strong>NORBIT AI</strong></div>'+aiOutput()+'</section></div>':
 '<section class="norbit-welcome"><span class="norbit-orbit">'+norbitMark+'</span><div class="norbit-kicker">UM POUCO DE CLAREZA. UM NOVO COMEÇO.</div><h1>O que vamos aprender hoje?</h1><p>Descomplique uma ideia. Crie conexões.<br>Transforme o que você estuda em algo que fica.</p><div class="norbit-suggestions">'+[['explain','Entender melhor','Uma explicação clara, com exemplos.','↗'],['cards','Memorizar uma ideia','Cartões que você pode editar e revisar.','▤'],['quiz','Testar o que sei','Questões para pensar antes de conferir.','✓']].map(([mode,title,description,icon])=>'<button data-action="ai-suggest" data-mode="'+mode+'"><span class="norbit-suggestion-icon" aria-hidden="true">'+icon+'</span><strong>'+title+'</strong><span>'+description+'</span></button>').join('')+'</div></section>')+
 '<div class="norbit-compose-wrap"><form id="ai-form" class="norbit-composer"><div class="ai-modes" role="group" aria-label="Ferramenta de IA">'+aiModes.map(([m,label])=>'<button type="button" data-action="ai-mode" data-mode="'+m+'" '+(aiBusy?'disabled':'')+' aria-pressed="'+(m===aiMode)+'">'+label+'</button>').join('')+'</div><label class="norbit-input-label" for="ai-content">Conteúdo para estudar</label><textarea id="ai-content" name="content" rows="4" minlength="20" maxlength="8000" required '+(aiBusy?'readonly':'')+' placeholder="Traga uma dúvida, um trecho do material ou uma questão…">'+esc(aiContent)+'</textarea><div class="norbit-compose-bottom"><span id="ai-length">'+aiContent.length+'/8.000</span><span class="norbit-keyhint">Ctrl + Enter para enviar</span><button type="submit" class="norbit-send" aria-label="Gerar com NORBIT AI" '+(aiBusy||!configured?'disabled':'')+'><span>'+ (aiBusy?'Preparando…':'Enviar')+'</span><svg viewBox="0 0 24 24" aria-hidden="true" fill="none"><path d="M12 19V5m-6 6 6-6 6 6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></button></div><div class="norbit-permission"><label class="checkbox-label ai-consent"><input type="checkbox" name="consent" required '+(aiBusy?'disabled':'')+'>Autorizo enviar este texto ao Google e ao Cloudflare para gerar a resposta.</label><div id="ai-verification" aria-label="Verificação de segurança"></div><p id="ai-security-status" role="status"></p></div>'+ (aiBusy?btn('Cancelar pedido','ai-cancel','','quiet small'):'')+(!configured?'<p class="note">A conexão com a IA ainda está sendo configurada.</p>':'')+'</form><p class="norbit-footnote">Só o texto escolhido é enviado. Confira as respostas antes de usar.</p><details class="norbit-details"><summary>Privacidade e limites de uso</summary><p>Seus registros e backups ficam neste aparelho. A verificação de segurança é carregada após sua autorização. As respostas da IA podem conter erros.</p><p>30 pedidos por dia para todo o site, até 10 por rede de acesso. Redes compartilhadas dividem esse limite. Tentativas enviadas ao serviço de IA também contam quando ele falha.</p><p>A conversa fica apenas nesta sessão. Cartões são guardados na sua preparação somente quando você decide salvar.</p></details></div></div>';
}
function aiFocusComposer(){requestAnimationFrame(()=>$('#ai-content')?.focus())}
function aiOutput(){
 if(aiResult?.cards&&exam()&&(aiExamId===null||aiExamId===exam().id))aiResult.cards.forEach(c=>{if(c.savedId)c.saved=exam().cards.some(x=>x.id===c.savedId)});
 if(aiBusy)return `<div class="ai-wait" role="status"><div class="norbit-thinking" aria-hidden="true"><i></i><i></i><i></i></div><h2>Conectando as ideias…</h2><p>Preparando ${aiMode==='cards'?'seus cartões':aiMode==='quiz'?'suas questões':'uma explicação'}. Você pode cancelar a qualquer momento.</p></div>`;
 if(aiError)return `<div class="note warn" role="alert">${esc(aiError)}</div>`;
 if(!aiResult)return `<div class="ai-empty"><span class="brand-mark" aria-hidden="true">n</span><h2>Uma ideia mais clara.</h2><p>Escolha uma ferramenta e envie um trecho. Sua resposta aparece aqui, pronta para conferir.</p><div class="separation"></div><p>Para memorizar melhor, tente responder com suas palavras antes de consultar a explicação.</p></div>`;
 if(aiResult.explanation)return `<div class="spread"><h2>Vamos entender.</h2>${btn('Copiar','ai-copy','','quiet small')}</div><div class="ai-prose">${esc(aiResult.explanation)}</div><p class="form-help">Explicação gerada por IA. Confira regras, datas e referências no seu material.</p>`;
 if(aiResult.cards)return `<h2>Confira seus cartões.</h2><p>Edite as perguntas e respostas antes de adicionar à revisão.</p>${exam()?.subjects.some(s=>!s.archived)?`<form id="ai-save-form"><label>Salvar na matéria<select name="subjectId" required>${subjectOptions()}</select></label>${aiResult.cards.map((c,i)=>`<div class="ai-draft"><label class="checkbox-label"><input name="select-${i}" type="checkbox" ${c.saved?'disabled':'checked'}>Cartão ${i+1}${c.saved?' · Salvo':''}</label><label>Pergunta<textarea name="front-${i}" rows="2" maxlength="12000" ${c.saved?'readonly':''}>${esc(c.front)}</textarea></label><label>Resposta<textarea name="back-${i}" rows="3" maxlength="12000" ${c.saved?'readonly':''}>${esc(c.back)}</textarea></label></div>`).join('')}<button class="primary" ${aiResult.cards.every(c=>c.saved)?'disabled':''}>Adicionar selecionados aos cartões</button></form>`:`<div class="note">Crie uma preparação com pelo menos uma matéria para salvar cartões.</div>${aiResult.cards.map(c=>`<div class="ai-draft"><h3>${esc(c.front)}</h3><p>${esc(c.back)}</p></div>`).join('')}`}`;
 return `<h2>Recupere antes de conferir.</h2><p>Questões inéditas de treino geradas por IA. Estes resultados não entram nas estatísticas da sua preparação.</p>${aiResult.questions.map((q,i)=>`<fieldset class="ai-question"><legend>${i+1}. ${esc(q.prompt)}</legend>${q.options.map((o,j)=>`<label class="ai-option"><input type="radio" name="ai-q-${i}" value="${j}" ${q.revealed?'disabled':''} ${q.choice===j?'checked':''}>${esc(o)}</label>`).join('')}${q.revealed?`<div class="note ${q.choice===q.answer?'':'warn'}">${q.choice===q.answer?'Você acertou.':'Vamos revisar.'} Resposta: ${esc(q.options[q.answer])}<p>${esc(q.explanation)}</p></div>`:btn('Conferir resposta','ai-answer',`data-index="${i}"`,'small')}</fieldset>`).join('')}`;
}
let aiTurnstileLoading=null;
function aiLoadTurnstile(){
 if(window.turnstile)return Promise.resolve();
 if(aiTurnstileLoading)return aiTurnstileLoading;
 aiTurnstileLoading=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;script.onload=resolve;script.onerror=()=>{script.remove();aiTurnstileLoading=null;reject(Error('Não foi possível carregar a verificação. Confira sua conexão.'))};document.head.append(script)});return aiTurnstileLoading;
}
async function aiVerify(){
 const container=$('#ai-verification');if(!container||!$('#ai-form [name="consent"]')?.checked||!AI_ENDPOINT.startsWith('https://'))return;
 try{await aiLoadTurnstile();if(!container.isConnected||!$('#ai-form [name="consent"]')?.checked)return;aiToken='';if(aiWidget!==null){window.turnstile.remove(aiWidget);aiWidget=null}aiWidget=window.turnstile.render(container,{sitekey:AI_SITEKEY,action:'study',theme:db.theme,language:'pt-br',callback:token=>{aiToken=token;if($('#ai-security-status'))$('#ai-security-status').textContent='Verificação concluída.'},'expired-callback':()=>{aiToken='';if($('#ai-security-status'))$('#ai-security-status').textContent='Verificação expirada. Aguarde a renovação.'},'error-callback':()=>{aiToken='';if($('#ai-security-status'))$('#ai-security-status').textContent='A verificação falhou. Recarregue a página e tente novamente.'}})}catch(e){if($('#ai-security-status'))$('#ai-security-status').textContent=e.message}
}
function aiCleanupWidget(){if(aiWidget!==null&&window.turnstile){window.turnstile.remove(aiWidget);aiWidget=null}aiToken=''}
async function aiSubmit(form){
 if(aiBusy)return;if(tour)return toast('Envios à IA ficam desativados durante o tutorial.');
 const content=form.elements.content.value.trim();aiContent=form.elements.content.value;
 if(content.length<20||content.length>8000)return toast('Envie de 20 a 8.000 caracteres.');
 if(!form.elements.consent.checked)return toast('Confirme o envio deste texto para continuar.');
 if(!aiToken)return toast('Aguarde ou conclua a verificação de segurança.');
 const token=aiToken,mode=aiMode;aiExamId=exam()?.id||null;aiCleanupWidget();aiSubmittedContent=content;aiBusy=true;aiError='';aiResult=null;aiController=new AbortController();const timeout=setTimeout(()=>aiController?.abort(),60000);render();
 try{const response=await fetch(AI_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,content,token}),signal:aiController.signal});const data=await response.json();if(!response.ok)throw Error(data.error||'Não foi possível concluir o pedido.');if(!aiValidResult(mode,data.result))throw Error('A resposta não veio no formato esperado.');aiResult=data.result}
 catch(e){aiError=e.name==='AbortError'?'Pedido cancelado ou tempo de espera esgotado. Nenhum cartão foi salvo.':e.message==='Failed to fetch'?'Não foi possível conectar à IA. Confira sua internet e tente novamente.':e.message.replace(/Gemini/g,'serviço de IA')}
 finally{clearTimeout(timeout);aiBusy=false;aiController=null;if(route==='ia'){render();requestAnimationFrame(()=>{const output=$('.ai-output');output?.focus({preventScroll:true});output?.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})})}}
}
function aiValidResult(mode,data){const text=x=>typeof x==='string'&&x.trim().length>0&&x.length<=12000;if(!data||typeof data!=='object')return false;if(mode==='explain')return text(data.explanation);if(mode==='cards')return Array.isArray(data.cards)&&data.cards.length===4&&data.cards.every(c=>c&&text(c.front)&&text(c.back));return Array.isArray(data.questions)&&data.questions.length===3&&data.questions.every(q=>q&&text(q.prompt)&&text(q.explanation)&&Array.isArray(q.options)&&q.options.length===4&&q.options.every(text)&&Number.isInteger(q.answer)&&q.answer>=0&&q.answer<4)}
Object.assign(actions,{
 'ai-open':()=>{if(tour)return toast('Saia da prática guiada para conversar com a NORBIT.');go('ia');aiFocusComposer()},
 'ai-new':()=>{if(aiBusy)return toast('Cancele o pedido atual antes de começar outra conversa.');aiCleanupWidget();aiContent='';aiSubmittedContent='';aiResult=null;aiError='';render();aiFocusComposer()},
 'ai-suggest':b=>{if(aiBusy)return;aiMode=b.dataset.mode;aiResult=null;aiError='';aiCleanupWidget();render();aiFocusComposer()},
 'ai-mode':b=>{if(aiBusy)return;aiContent=$('#ai-content')?.value||aiContent;aiMode=b.dataset.mode;aiResult=null;aiError='';aiCleanupWidget();render()},
 'ai-cancel':()=>aiController?.abort(),
 'ai-copy':async()=>{try{await navigator.clipboard.writeText(aiResult.explanation);toast('Explicação copiada.')}catch{toast('Selecione a explicação para copiar.')}},
 'ai-answer':b=>{const i=+b.dataset.index,q=aiResult?.questions?.[i],choice=$(`input[name="ai-q-${i}"]:checked`);if(!q||!choice)return toast('Escolha uma alternativa antes de conferir.');q.choice=+choice.value;q.revealed=true;const field=b.closest('fieldset');field.insertAdjacentHTML('beforeend',`<div class="note ${q.choice===q.answer?'':'warn'}">${q.choice===q.answer?'Você acertou.':'Vamos revisar.'} Resposta: ${esc(q.options[q.answer])}<p>${esc(q.explanation)}</p></div>`);$$('input',field).forEach(x=>x.disabled=true);b.remove()},
 'ai-from-mistake':b=>{if(tour)return toast('A IA fica desativada durante a prática.');const m=exam()?.mistakes.find(x=>x.id===b.dataset.id);if(!m)return;aiMode='explain';aiResult=null;aiError='';aiContent=`Minha dificuldade: ${m.title}\nMinha explicação atual: ${m.explanation||''}`;go('ia')}
});
document.addEventListener('input',event=>{if(event.target.id==='ai-content'){aiContent=event.target.value;if($('#ai-length'))$('#ai-length').textContent=aiContent.length+'/8.000'}});
document.addEventListener('change',event=>{if(event.target.name==='consent'&&event.target.closest('#ai-form')){if(event.target.checked)aiVerify();else{aiCleanupWidget();if($('#ai-security-status'))$('#ai-security-status').textContent=''}}});
document.addEventListener('submit',event=>{
 if(event.target.id==='ai-form'){event.preventDefault();aiSubmit(event.target)}
 if(event.target.id==='ai-save-form'){
  event.preventDefault();if(tour)return toast('Saia do tutorial para salvar cartões.');const e=exam();if(!e||(aiExamId!==null&&aiExamId!==e.id))return toast('Volte à preparação em que os cartões foram gerados.');
  try{const d=new FormData(event.target),sid=d.get('subjectId');if(!e.subjects.some(s=>s.id===sid&&!s.archived))throw Error('Selecione uma matéria válida.');const selected=aiResult.cards.map((c,i)=>({c,i})).filter(({c,i})=>!c.saved&&d.has(`select-${i}`));if(!selected.length)throw Error('Selecione pelo menos um cartão.');const cards=selected.map(({c,i})=>{const front=String(d.get(`front-${i}`)||'').trim(),back=String(d.get(`back-${i}`)||'').trim();if(!front||!back||front.length>12000||back.length>12000)throw Error('Confira a pergunta e a resposta de cada cartão selecionado.');return {id:id(),subjectId:sid,topicId:null,front,back,due:today(),interval:0,reps:0,suspended:false}});snapshot();aiExamId=e.id;e.cards.push(...cards);selected.forEach(({c},i)=>{Object.assign(c,{front:cards[i].front,back:cards[i].back,saved:true,savedId:cards[i].id})});commit(`${cards.length} cartões adicionados à revisão.`,true)}catch(e){toast(e.message)}
 }
});
window.addEventListener('hashchange',()=>{if(route!=='ia')aiCleanupWidget()});

document.addEventListener('keydown',event=>{if(event.target.id==='ai-content'&&(event.ctrlKey||event.metaKey)&&event.key==='Enter'){event.preventDefault();$('#ai-form')?.requestSubmit()}});
