// Public configuration only. API and Turnstile secrets belong to Cloudflare.
const AI_ENDPOINT='https://norte-gemini.joaovitorgoncalvesdev.workers.dev/ai';
const AI_SITEKEY='0x4AAAAAAFRsSVvCJLFjoSbn';
let aiMode='explain',aiContent='',aiResult=null,aiError='',aiBusy=false,aiController=null,aiWidget=null,aiToken='',aiExamId=null;
const aiModes=[['explain','Entender uma dificuldade'],['cards','Criar cartões'],['quiz','Praticar questões']];
const norbitMark='<svg viewBox="0 0 32 32" fill="none" aria-hidden="true"><path d="M8 23V9l16 14V9" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/><ellipse cx="16" cy="16" rx="14" ry="7" transform="rotate(-35 16 16)" stroke="currentColor" stroke-width="1.2" opacity=".5"/></svg>';
let aiSubmittedContent='',aiQuizIndex=0,aiUseContext=false,aiQuestionCount=3,aiDifficulty='medium',aiGeneratedDifficulty='medium';
function aiStudyContext(){
 const e=exam();if(!e)return '';
 const short=(value,max=140)=>String(value||'').replace(/\s+/g,' ').trim().slice(0,max);
 const recent=stats(periodSessions(7,e)),topics=allTopics(e),subjects=e.subjects.filter(s=>!s.archived).slice(0,15);
 const upcoming=e.plans.filter(p=>p.status==='planned'&&p.date>=today()&&p.date<=addDays(today(),7)).sort((a,b)=>a.date.localeCompare(b.date)||a.start.localeCompare(b.start)).slice(0,12);
 const lines=['Preparação ativa: '+short(e.name),...(studyKind(e)==='concurso'?['Cargo: '+(short(e.position)||'Não informado'),'Banca: '+(short(e.board)||'Não informada')]:[]),studyKinds[studyKind(e)].date+': '+(e.date||'Não informada'),'Metas: '+e.dailyMinutes+' minutos e '+e.dailyQuestions+' questões por dia; '+e.weeklyMinutes+' minutos por semana; '+e.targetAccuracy+'% de acerto.','Últimos 7 dias: '+recent.m+' minutos estudados; '+recent.q+' questões; '+(recent.accuracy===null?'sem taxa de acerto registrada':recent.accuracy+'% de acerto')+'.','Matérias (até 15):'];
 subjects.forEach(s=>{const subset=topics.filter(x=>x.s.id===s.id),covered=subset.filter(x=>['covered','mastered'].includes(x.t.stage)).length;lines.push('- '+short(s.name)+': '+covered+' de '+subset.length+' assuntos estudados; peso '+s.weight+'.')});
 lines.push('Próximas atividades planejadas (até 12, próximos 7 dias):');
 if(!upcoming.length)lines.push('Nenhuma atividade planejada nesse período.');
 upcoming.forEach(p=>lines.push('- '+p.date+' '+p.start+'–'+p.end+' | '+short(subjectName(p.subjectId))+' | '+short(topicName(p.subjectId,p.topicId))+' | '+short(p.type,40)));
 lines.push('Prioridades calculadas pelo painel (até 3):');recommendations().slice(0,3).forEach(x=>lines.push('- '+short(x.s.name)+' / '+short(x.t.name)+' | '+short(reason(x.s,x.t))));
 return [deadlineAIContext(e),...lines].filter(Boolean).join('\n').slice(0,8000);
}
function aiContextControl(context=aiStudyContext()){return '<div class="ai-context-control"><label class="checkbox-label"><input type="checkbox" name="studyContext" '+(aiUseContext&&context?'checked':'')+' '+(!context||aiBusy?'disabled':'')+'><span><strong>Usar minha preparação como contexto</strong><small>'+ (context?'Metas, matérias, prazos e desempenho recente.':'Crie uma preparação para receber respostas mais pessoais.')+'</small></span></label>'+ (context&&aiUseContext?'<details class="ai-context-preview"><summary>Conferir o contexto que será enviado</summary><pre>'+esc(context)+'</pre></details>':'')+'</div>'}
function viewAITools(){
 const configured=AI_ENDPOINT.startsWith('https://')&&!AI_SITEKEY.startsWith('__');
 const active=aiBusy||aiResult||aiError,studyContext=aiStudyContext();
 return (tour?'<div class="note">Prática do tutorial: respostas de demonstração, sem envio à IA.</div>':'')+'<div class="norbit-page'+(active?' has-answer':'')+'"><header class="norbit-header"><div class="norbit-identity"><span class="norbit-symbol">'+norbitMark+'</span><span><strong>NORBIT <span>AI</span></strong><small>Seu parceiro de estudos</small></span></div>'+btn('Nova conversa','ai-new','','quiet small')+'</header>'+
 (active?'<h1 class="norbit-sr">Conversa com NORBIT AI</h1><div class="norbit-thread"><div class="norbit-user"><span class="norbit-message-label">Você · '+esc(aiModes.find(m=>m[0]===aiMode)?.[1]||'Estudar')+'</span><p>'+esc(aiSubmittedContent||aiContent)+'</p></div><section class="ai-output norbit-answer" aria-label="Resposta da NORBIT AI" aria-busy="'+aiBusy+'" tabindex="-1"><div class="norbit-answer-byline"><span class="norbit-symbol">'+norbitMark+'</span><strong>NORBIT AI</strong></div>'+aiOutput()+'</section></div>':
 '<section class="norbit-welcome">'+norbitMascot('welcome','ai')+'<span class="norbit-orbit">'+norbitMark+'</span><div class="norbit-kicker">UM POUCO DE CLAREZA. UM NOVO COMEÇO.</div><h1>O que vamos aprender hoje?</h1><p>Descomplique uma ideia. Crie conexões.<br>Transforme o que você estuda em algo que fica.</p><div class="norbit-suggestions">'+[['explain','Entender melhor','Uma explicação clara, com exemplos.','↗'],['cards','Memorizar uma ideia','Cartões que você pode editar e revisar.','▤'],['quiz','Testar o que sei','Questões para pensar antes de conferir.','✓']].map(([mode,title,description,icon])=>'<button data-action="ai-suggest" data-mode="'+mode+'"><span class="norbit-suggestion-icon" aria-hidden="true">'+icon+'</span><strong>'+title+'</strong><span>'+description+'</span></button>').join('')+'</div></section>')+
 '<div class="norbit-compose-wrap">'+aiContextControl(studyContext)+'<form id="ai-form" class="norbit-composer"><div class="ai-modes" role="group" aria-label="Ferramenta de IA">'+aiModes.map(([m,label])=>'<button type="button" data-action="ai-mode" data-mode="'+m+'" '+(aiBusy?'disabled':'')+' aria-pressed="'+(m===aiMode)+'">'+label+'</button>').join('')+'</div>'+aiQuizSettings()+'<label class="norbit-input-label" for="ai-content">Conteúdo para estudar</label><textarea id="ai-content" name="content" rows="4" minlength="20" maxlength="8000" required '+(aiBusy?'readonly':'')+' placeholder="Traga uma dúvida, um trecho do material ou uma questão…">'+esc(aiContent)+'</textarea><div class="norbit-compose-bottom"><span id="ai-length">'+aiContent.length+'/8.000</span><span class="norbit-keyhint">Ctrl + Enter para enviar</span><button type="submit" class="norbit-send" aria-label="Gerar com NORBIT AI" '+(aiBusy||!configured?'disabled':'')+'><span>'+ (aiBusy?'Preparando…':'Enviar')+'</span><svg viewBox="0 0 24 24" aria-hidden="true" fill="none"><path d="M12 19V5m-6 6 6-6 6 6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></button></div><div class="norbit-permission"><p class="ai-send-notice">Ao enviar, sua mensagem e o histórico recente deste chat são enviados à IA. O resumo da preparação só é enviado se você ativá-lo acima. As notas de um material são enviadas somente quando você o seleciona como referência.</p><div id="ai-verification" aria-label="Verificação de segurança"></div><p id="ai-security-status" role="status"></p></div>'+ (aiBusy?btn('Cancelar pedido','ai-cancel','','quiet small'):'')+(!configured?'<p class="note">A conexão com a IA ainda está sendo configurada.</p>':'')+'</form><p class="norbit-footnote">'+(aiUseContext&&studyContext?'Texto e contexto selecionados são enviados. Confira as respostas antes de usar.':'A mensagem, o histórico recente e a referência selecionada são enviados. Confira as respostas antes de usar.')+'</p><details class="norbit-details"><summary>Privacidade e limites de uso</summary><p>Seus registros e backups ficam neste aparelho. Se você ativar o contexto, apenas o resumo exibido é enviado com seu texto; anotações, links e backups não entram no resumo. A verificação de segurança é carregada após sua autorização. As respostas da IA podem conter erros.</p><p>30 pedidos por dia para todo o site, até 10 por rede de acesso. Redes compartilhadas dividem esse limite. Tentativas enviadas ao serviço de IA também contam quando ele falha.</p><p>A conversa fica apenas nesta sessão. Cartões são guardados na sua preparação somente quando você decide salvar.</p></details></div></div>';
}
function aiQuizSettings(){if(aiMode!=='quiz')return '';return '<div class="ai-quiz-settings"><label>Quantidade de questões<select name="questionCount" '+(aiBusy?'disabled':'')+'>'+Array.from({length:10},(_,i)=>'<option value="'+(i+1)+'" '+(aiQuestionCount===i+1?'selected':'')+'>'+(i+1)+(i===0?' questão':' questões')+'</option>').join('')+'</select></label><label>Dificuldade<select name="difficulty" '+(aiBusy?'disabled':'')+'>'+[['easy','Fácil · reconhecer'],['medium','Médio · aplicar'],['hard','Difícil · conectar conceitos']].map(([value,label])=>'<option value="'+value+'" '+(aiDifficulty===value?'selected':'')+'>'+label+'</option>').join('')+'</select></label></div>'}
function aiFocusComposer(){requestAnimationFrame(()=>$('#ai-content')?.focus())}
function aiOutput(){
 if(aiResult?.cards&&exam()&&(aiExamId===null||aiExamId===exam().id))aiResult.cards.forEach(c=>{if(c.savedId)c.saved=exam().cards.some(x=>x.id===c.savedId)});
 if(aiBusy)return `<div class="ai-wait" role="status">${norbitMascot('thinking','small')}<h2>Conectando as ideias…</h2><p>Preparando ${aiMode==='cards'?'seus cartões':aiMode==='quiz'?'suas questões':'uma explicação'}. Você pode cancelar a qualquer momento.</p></div>`;
 if(aiError)return `<div class="note warn" role="alert">${esc(aiError)}</div>`;
 if(!aiResult)return `<div class="ai-empty"><span class="brand-mark" aria-hidden="true">n</span><h2>Uma ideia mais clara.</h2><p>Escolha uma ferramenta e envie um trecho. Sua resposta aparece aqui, pronta para conferir.</p><div class="separation"></div><p>Para memorizar melhor, tente responder com suas palavras antes de consultar a explicação.</p></div>`;
 if(aiResult.explanation)return `<div class="spread"><h2>Vamos entender.</h2>${btn('Copiar','ai-copy','','quiet small')}</div><div class="ai-prose">${esc(aiResult.explanation)}</div><p class="form-help">Explicação gerada por IA. Confira regras, datas e referências no seu material.</p>`;
 if(aiResult.cards)return `<h2>Confira seus cartões.</h2><p>Edite as perguntas e respostas antes de adicionar à revisão.</p>${exam()?.subjects.some(s=>!s.archived)?`<form id="ai-save-form"><label>Salvar na matéria<select name="subjectId" required>${subjectOptions()}</select></label>${aiResult.cards.map((c,i)=>`<div class="ai-draft"><label class="checkbox-label"><input name="select-${i}" type="checkbox" ${c.saved?'disabled':'checked'}>Cartão ${i+1}${c.saved?' · Salvo':''}</label><label>Pergunta<textarea name="front-${i}" rows="2" maxlength="12000" ${c.saved?'readonly':''}>${esc(c.front)}</textarea></label><label>Resposta<textarea name="back-${i}" rows="3" maxlength="12000" ${c.saved?'readonly':''}>${esc(c.back)}</textarea></label></div>`).join('')}<button class="primary" ${aiResult.cards.every(c=>c.saved)?'disabled':''}>Adicionar selecionados aos cartões</button></form>`:`<div class="note">Crie uma preparação com pelo menos uma matéria para salvar cartões.</div>${aiResult.cards.map(c=>`<div class="ai-draft"><h3>${esc(c.front)}</h3><p>${esc(c.back)}</p></div>`).join('')}`}`;
 return aiQuizOutput();
}
function aiQuizOutput(){
 const questions=aiResult.questions,total=questions.length,answered=questions.filter(q=>q.revealed).length,correct=questions.filter(q=>q.revealed&&q.choice===q.answer).length;
 aiQuizIndex=Math.max(0,Math.min(total-1,aiQuizIndex));const q=questions[aiQuizIndex],i=aiQuizIndex;
 return '<div class="norbit-quiz"><div class="ai-quiz-intro"><div><span class="ai-quiz-eyebrow">PRÁTICA ATIVA · '+({easy:'FÁCIL',medium:'MÉDIO',hard:'DIFÍCIL'}[aiGeneratedDifficulty]||'MÉDIO')+'</span><h2>Uma questão de cada vez.</h2><p>Escolha uma alternativa. Confira o raciocínio e siga no seu ritmo.</p></div><span class="ai-quiz-count">'+answered+' de '+total+' respondidas</span></div><div class="ai-quiz-progress" role="progressbar" aria-label="Questões respondidas" aria-valuemin="0" aria-valuemax="'+total+'" aria-valuenow="'+answered+'"><span style="width:'+answered/total*100+'%"></span></div><nav class="ai-quiz-tabs" aria-label="Navegar pelas questões">'+questions.map((item,n)=>'<button type="button" data-action="ai-question-go" data-index="'+n+'" aria-current="'+(n===i?'step':'false')+'" class="'+(item.revealed?(item.choice===item.answer?'is-correct':'is-wrong'):'')+'"><span>Questão '+(n+1)+'</span><span aria-hidden="true">'+(item.revealed?(item.choice===item.answer?'✓':'×'):'')+'</span><span class="norbit-sr">'+(item.revealed?(item.choice===item.answer?'Respondida corretamente':'Respondida incorretamente'):'Ainda não respondida')+'</span></button>').join('')+'</nav><div id="ai-question-slot">'+aiQuestionCard(q,i,total)+'</div><div class="ai-quiz-summary" role="status">'+(answered===total?'<strong>Treino concluído · '+correct+' de '+total+' acertos</strong><p>'+ (correct===total?'Muito bem. Tente explicar a regra sem consultar a resposta.':'Retome as justificativas das questões que errou. Esse é seu próximo passo.')+'</p>'+btn('Recomeçar este treino','ai-quiz-restart','','secondary small'):'<p>Seu resultado fica só neste treino e não altera as estatísticas da preparação.</p>')+'</div><p class="ai-quiz-disclaimer">Questões de treino geradas por IA. Confira as explicações no seu material.</p></div>';
}
function aiQuestionCard(q,i,total){
 const letters='ABCD',correct=q.choice===q.answer;
 return '<fieldset class="ai-question"><legend class="norbit-sr">Questão '+(i+1)+': '+esc(q.prompt)+'</legend><div class="ai-question-top"><span>QUESTÃO '+String(i+1).padStart(2,'0')+'</span><span>'+ (q.revealed?'Resposta conferida':'Uma alternativa correta')+'</span></div><h3 class="ai-question-title" tabindex="-1">'+esc(q.prompt)+'</h3><div class="ai-options">'+q.options.map((option,j)=>'<label class="ai-option '+(q.revealed?(j===q.answer?'is-correct':j===q.choice?'is-wrong':'is-muted'):'')+'"><input type="radio" name="ai-q-'+i+'" value="'+j+'" '+(q.revealed?'disabled':'')+' '+(q.choice===j?'checked':'')+'><span class="ai-option-letter" aria-hidden="true">'+letters[j]+'</span><span class="ai-option-copy">'+esc(option)+(q.revealed&&(j===q.answer||j===q.choice)?'<small>'+ (j===q.answer?'✓ Alternativa correta':'× Sua resposta · incorreta')+'</small>':'')+'</span></label>').join('')+'</div>'+ (q.revealed?'<section class="ai-feedback '+(correct?'is-correct':'is-wrong')+'" tabindex="-1" aria-label="Resultado da questão">'+norbitMascot(correct?'success':'encourage','small')+'<div class="ai-feedback-title"><span aria-hidden="true">'+(correct?'✓':'×')+'</span><h4>'+ (correct?'Você acertou!':'Você errou. Vamos entender.')+'</h4></div><p>'+ (correct?'Sua resposta está correta.':'Você marcou '+letters[q.choice]+'. A alternativa correta é '+letters[q.answer]+'.')+'</p></section><div class="ai-rationale"><span class="ai-quiz-eyebrow">ENTENDA O RACIOCÍNIO</span><h4>Por que '+letters[q.answer]+' é a resposta?</h4><p class="ai-rationale-text">'+esc(q.explanation)+'</p>'+ (Array.isArray(q.optionExplanations)?'<details class="ai-alternative-reasons"><summary>Entenda cada alternativa</summary><div>'+q.optionExplanations.map((reason,j)=>'<section><strong>'+letters[j]+' · '+(j===q.answer?'Correta':'Incorreta')+'</strong><p>'+esc(reason)+'</p></section>').join('')+'</div></details>':'')+(q.takeaway?'<div class="ai-takeaway"><strong>Para levar à próxima questão</strong><p>'+esc(q.takeaway)+'</p></div>':'')+'</div>':'<div class="ai-question-confirm"><p id="ai-choice-hint">'+(Number.isInteger(q.choice)?'Tudo pronto. Confira sua resposta.':'Selecione uma alternativa para responder.')+'</p><button type="button" class="primary" data-action="ai-answer" data-index="'+i+'" '+(Number.isInteger(q.choice)?'':'disabled')+'>Responder questão</button></div>')+'<div class="ai-question-navigation">'+btn('Anterior','ai-question-go','data-index="'+(i-1)+'" '+(i===0?'disabled':''),'quiet small')+'<span>'+(i+1)+' / '+total+'</span>'+btn('Próxima','ai-question-go','data-index="'+(i+1)+'" '+(i===total-1?'disabled':''),'secondary small')+'</div></fieldset>';
}
function aiRefreshQuiz(focusResult=false){if(!tour&&aiCurrentChat())aiChatSave();const host=$('.norbit-quiz');if(!host)return;host.outerHTML=aiQuizOutput();const target=$(focusResult?'.ai-feedback':'.ai-question-title');target?.focus({preventScroll:true});if(!focusResult)target?.scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}

let aiTurnstileLoading=null,aiAwaitingVerification=false;
function aiLoadTurnstile(){
 if(window.turnstile)return Promise.resolve();
 if(aiTurnstileLoading)return aiTurnstileLoading;
 aiTurnstileLoading=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;script.onload=resolve;script.onerror=()=>{script.remove();aiTurnstileLoading=null;reject(Error('Não foi possível carregar a verificação. Confira sua conexão.'))};document.head.append(script)});return aiTurnstileLoading;
}
async function aiVerify(){
 if(tour){if($('#ai-security-status'))$('#ai-security-status').textContent='Modo de prática. Nenhuma verificação ou envio externo.';return}
 const container=$('#ai-verification');if(!container||!aiAwaitingVerification||!AI_ENDPOINT.startsWith('https://'))return;
 try{await aiLoadTurnstile();if(!container.isConnected||!aiAwaitingVerification)return;aiToken='';if(aiWidget!==null){window.turnstile.remove(aiWidget);aiWidget=null}aiWidget=window.turnstile.render(container,{sitekey:AI_SITEKEY,action:'study',theme:db.theme,language:'pt-br',callback:token=>{aiToken=token;if($('#ai-security-status'))$('#ai-security-status').textContent='Verificação concluída.';if(aiAwaitingVerification){requestAnimationFrame(()=>$('#ai-form')?.requestSubmit())}},'expired-callback':()=>{aiToken='';if($('#ai-security-status'))$('#ai-security-status').textContent='Verificação expirada. Aguarde a renovação.'},'error-callback':()=>{aiToken='';aiAwaitingVerification=false;if($('#ai-security-status'))$('#ai-security-status').textContent='A verificação falhou. Recarregue a página e tente novamente.'}})}catch(e){aiAwaitingVerification=false;if($('#ai-security-status'))$('#ai-security-status').textContent=e.message}
}
function aiCleanupWidget(){aiAwaitingVerification=false;if(aiWidget!==null&&window.turnstile){window.turnstile.remove(aiWidget);aiWidget=null}aiToken=''}
async function aiSubmit(form){
 if(aiBusy)return;if(tour){if(!form.reportValidity())return;return studyAIPractice(aiMode)}
 const content=form.elements.content.value.trim();aiContent=form.elements.content.value;
 if(content.length<(aiCurrentChat()?.messages.length?1:20)||content.length>8000)return toast('Envie de 20 a 8.000 caracteres.');
 if(!aiToken){if(aiAwaitingVerification)return;aiAwaitingVerification=true;if($('#ai-security-status'))$('#ai-security-status').innerHTML='Confirme que é humano para enviar. '+btn('Cancelar envio','ai-cancel-verification','','quiet small');aiVerify();return}
 let chatTurn;try{chatTurn=aiChatBegin(content,aiMode)}catch(e){return toast(e.message)}
 const token=aiToken,mode=aiMode,context=aiUseContext?aiStudyContext():'',questionCount=aiQuestionCount,difficulty=aiDifficulty;aiGeneratedDifficulty=difficulty;aiExamId=exam()?.id||null;aiCleanupWidget();aiSubmittedContent=content;aiQuizIndex=0;aiBusy=true;aiError='';aiResult=null;aiController=new AbortController();const timeout=setTimeout(()=>aiController?.abort(),60000);render();
 try{const sourceText=tutorSourceText();const response=await fetch(AI_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,content,token,history:chatTurn.history,tool:mode==='explain'?tutorTool:'explain',responseStyle:norbitDepth,...(sourceText?{sourceText}:{}),...(context?{context}:{}),...(mode==='quiz'?{questionCount,difficulty}:{})}),signal:aiController.signal});const data=await response.json();if(!response.ok)throw Error(data.error||'Não foi possível concluir o pedido.');if(!aiValidResult(mode,data.result,questionCount))throw Error('A resposta não veio no formato esperado.');tutorRemaining=Number.isInteger(data.remaining)?data.remaining:tutorRemaining;aiResult=data.result;aiContent='';aiChatFinish(chatTurn,aiResult,'')}
 catch(e){aiError=e.name==='AbortError'?'Pedido cancelado ou tempo de espera esgotado. Nenhum cartão foi salvo.':e.message==='Failed to fetch'?'Não foi possível conectar à IA. Confira sua internet e tente novamente.':e.message.replace(/Gemini/g,'serviço de IA')}
 finally{if(aiError)aiChatFinish(chatTurn,null,aiError);clearTimeout(timeout);aiBusy=false;aiController=null;if(route==='ia'){render();requestAnimationFrame(()=>{const output=$$('.norbit-thread > *').at(-1)||$('.ai-output');output?.focus({preventScroll:true});output?.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})})}}
}
function aiValidResult(mode,data,questionCount=3){const text=x=>typeof x==='string'&&x.trim().length>0&&x.length<=12000;if(!data||typeof data!=='object')return false;if(mode==='explain')return text(data.explanation);if(mode==='cards')return Array.isArray(data.cards)&&data.cards.length===4&&data.cards.every(c=>c&&text(c.front)&&text(c.back));return Array.isArray(data.questions)&&data.questions.length===questionCount&&data.questions.every(q=>q&&text(q.prompt)&&text(q.explanation)&&Array.isArray(q.options)&&q.options.length===4&&q.options.every(text)&&Number.isInteger(q.answer)&&q.answer>=0&&q.answer<4)}
Object.assign(actions,{
 'ai-open':()=>{if(tour)return toast('Saia da prática guiada para conversar com a NORBIT.');go('ia');aiFocusComposer()},
 'ai-new':()=>{if(aiBusy)return toast('Cancele o pedido atual antes de começar outra conversa.');aiCleanupWidget();aiContent='';aiSubmittedContent='';aiResult=null;aiError='';render();aiFocusComposer()},
 'ai-suggest':b=>{if(aiBusy)return;aiMode=b.dataset.mode;aiResult=null;aiError='';aiCleanupWidget();render();aiFocusComposer()},
 'ai-mode':b=>{if(aiBusy)return;aiContent=$('#ai-content')?.value||aiContent;aiMode=b.dataset.mode;aiResult=null;aiError='';aiCleanupWidget();render()},
 'ai-cancel':()=>aiController?.abort(),
 'ai-cancel-verification':()=>{aiCleanupWidget();if($('#ai-security-status'))$('#ai-security-status').textContent='Envio cancelado.'},
 'ai-copy':async()=>{try{await navigator.clipboard.writeText(aiResult.explanation);toast('Explicação copiada.')}catch{toast('Selecione a explicação para copiar.')}},
 'ai-answer':b=>{const i=+b.dataset.index,q=aiResult?.questions?.[i];if(!q||q.revealed)return;if(!Number.isInteger(q.choice))return toast('Selecione uma alternativa antes de responder.');q.revealed=true;aiRefreshQuiz(true)},
 'ai-question-go':b=>{const index=+b.dataset.index;if(!aiResult?.questions||index<0||index>=aiResult.questions.length)return;aiQuizIndex=index;aiRefreshQuiz()},
 'ai-quiz-restart':()=>{if(!aiResult?.questions)return;aiResult.questions.forEach(q=>{delete q.choice;delete q.revealed});aiQuizIndex=0;aiRefreshQuiz();toast('Treino reiniciado. Nenhum novo pedido à IA foi feito.')},
 'ai-from-mistake':b=>{if(aiBusy)return toast('Aguarde ou cancele o pedido atual.');aiChatId=null;if(tour)return toast('A IA fica desativada durante a prática.');const m=exam()?.mistakes.find(x=>x.id===b.dataset.id);if(!m)return;aiMode='explain';aiResult=null;aiError='';aiContent=`Minha dificuldade: ${m.title}\nMinha explicação atual: ${m.explanation||''}`;go('ia')}
});
document.addEventListener('input',event=>{if(event.target.id==='ai-content'){aiContent=event.target.value;if($('#ai-length'))$('#ai-length').textContent=aiContent.length+'/8.000'}});
document.addEventListener('submit',event=>{
 if(event.target.id==='ai-form'){event.preventDefault();aiSubmit(event.target)}
 if(event.target.id==='ai-save-form'){
  event.preventDefault();if(tour)return toast('Saia do tutorial para salvar cartões.');const e=exam();if(!e||(aiExamId!==null&&aiExamId!==e.id))return toast('Volte à preparação em que os cartões foram gerados.');
  try{const d=new FormData(event.target),sid=d.get('subjectId');if(!e.subjects.some(s=>s.id===sid&&!s.archived))throw Error('Selecione uma matéria válida.');const selected=aiResult.cards.map((c,i)=>({c,i})).filter(({c,i})=>!c.saved&&d.has(`select-${i}`));if(!selected.length)throw Error('Selecione pelo menos um cartão.');const cards=selected.map(({c,i})=>{const front=String(d.get(`front-${i}`)||'').trim(),back=String(d.get(`back-${i}`)||'').trim();if(!front||!back||front.length>12000||back.length>12000)throw Error('Confira a pergunta e a resposta de cada cartão selecionado.');return {id:id(),subjectId:sid,topicId:null,front,back,due:today(),interval:0,reps:0,suspended:false}});snapshot();aiExamId=e.id;e.cards.push(...cards);selected.forEach(({c},i)=>{Object.assign(c,{front:cards[i].front,back:cards[i].back,saved:true,savedId:cards[i].id})});commit(`${cards.length} cartões adicionados à revisão.`,true)}catch(e){toast(e.message)}
 }
});
window.addEventListener('hashchange',()=>{if(route!=='ia')aiCleanupWidget()});

document.addEventListener('keydown',event=>{if(event.target.id==='ai-content'&&(event.ctrlKey||event.metaKey)&&event.key==='Enter'){event.preventDefault();$('#ai-form')?.requestSubmit()}});

document.addEventListener('change',event=>{const input=event.target;if(input.type!=='radio'||!input.name.startsWith('ai-q-'))return;const index=Number(input.name.slice(5)),q=aiResult?.questions?.[index],choice=Number(input.value);if(!q||q.revealed||!Number.isInteger(choice)||choice<0||choice>3)return;q.choice=choice;const card=input.closest('.ai-question'),button=$('[data-action="ai-answer"]',card);if(button)button.disabled=false;const hint=$('#ai-choice-hint',card);if(hint)hint.textContent='Tudo pronto. Confira sua resposta.'});

document.addEventListener('change',event=>{if(event.target.name!=='studyContext')return;aiContent=$('#ai-content')?.value||aiContent;aiUseContext=event.target.checked;aiCleanupWidget();render();requestAnimationFrame(()=>$('[name="studyContext"]')?.focus({preventScroll:true}))});


document.addEventListener('change',event=>{if(!event.target.closest('#ai-form'))return;if(event.target.name==='questionCount'){const count=Number(event.target.value);if(Number.isInteger(count)&&count>=1&&count<=10)aiQuestionCount=count}if(event.target.name==='difficulty'&&['easy','medium','hard'].includes(event.target.value))aiDifficulty=event.target.value});
