// Public configuration only. API and Turnstile secrets belong to Cloudflare.
const AI_ENDPOINT='https://norte-gemini.joaovitorgoncalvesdev.workers.dev/ai';
const AI_SITEKEY='0x4AAAAAAFRsSVvCJLFjoSbn';
let aiMode='explain',aiContent='',aiResult=null,aiError='',aiBusy=false,aiController=null,aiWidget=null,aiToken='',aiExamId=null;
const aiModes=[['explain','Entender uma dificuldade'],['cards','Criar cartões'],['quiz','Praticar questões']];
function viewAI(){
 const configured=AI_ENDPOINT.startsWith('https://')&&!AI_SITEKEY.startsWith('__');
 return heading('Estude com uma segunda explicação.','Use o Gemini para entender, recuperar e praticar. Você continua no comando.')+`<div class="grid two ai-layout"><section class="panel"><div class="tag blue">Gemini · Assistente de estudos</div><h2 style="margin-top:16px">O que vamos trabalhar?</h2><div class="ai-modes" role="group" aria-label="Ferramenta de IA">${aiModes.map(([m,label])=>`<button data-action="ai-mode" data-mode="${m}" ${aiBusy?'disabled':''} aria-pressed="${m===aiMode}" class="${m===aiMode?'primary':''}">${label}</button>`).join('')}</div><form id="ai-form"><label>Conteúdo para estudar<textarea id="ai-content" name="content" rows="9" minlength="20" maxlength="8000" required ${aiBusy?'readonly':''} placeholder="Cole um trecho do seu material, uma questão ou descreva uma dificuldade. Não inclua dados pessoais.">${esc(aiContent)}</textarea></label><div class="spread"><small>De 20 a 8.000 caracteres</small><small id="ai-length">${aiContent.length}/8.000</small></div><label class="checkbox-label ai-consent"><input type="checkbox" name="consent" required ${aiBusy?'disabled':''}>Autorizo enviar somente este texto ao Google Gemini e ao Cloudflare para gerar a resposta.</label><p class="form-help">Seus registros e backups não são enviados. A proteção contra abuso é carregada ao marcar esta opção. As respostas da IA podem conter erros; confira seu material antes de salvar.</p><div id="ai-verification" aria-label="Verificação de segurança"></div><p id="ai-security-status" class="form-help" role="status"></p><div class="actions"><button type="submit" class="primary" ${aiBusy||!configured?'disabled':''}>${aiBusy?'Preparando sua resposta…':'Gerar com Gemini'}</button>${aiBusy?btn('Cancelar pedido','ai-cancel'):''}</div>${!configured?'<p class="note">A conexão com a IA ainda está sendo configurada.</p>':''}<p class="form-help">Limite inicial: 30 pedidos por dia para o site, até 10 por acesso. Redes compartilhadas dividem esse limite. Tentativas enviadas ao Gemini também contam quando ele falha.</p></form></section><section class="panel ai-output" aria-label="Resposta do assistente" aria-busy="${aiBusy}">${aiOutput()}</section></div>`;
}
function aiOutput(){
 if(aiResult?.cards&&exam()&&(aiExamId===null||aiExamId===exam().id))aiResult.cards.forEach(c=>{if(c.savedId)c.saved=exam().cards.some(x=>x.id===c.savedId)});
 if(aiBusy)return `<div class="ai-wait" role="status"><span class="ai-pulse" aria-hidden="true"></span><h2>Construindo uma explicação.</h2><p>Você pode cancelar a qualquer momento.</p></div>`;
 if(aiError)return `<div class="note warn" role="alert">${esc(aiError)}</div>`;
 if(!aiResult)return `<div class="ai-empty"><span class="brand-mark" aria-hidden="true">n</span><h2>Uma ideia mais clara.</h2><p>Escolha uma ferramenta e envie um trecho. Sua resposta aparece aqui, pronta para conferir.</p><div class="separation"></div><p>Para memorizar melhor, tente responder com suas palavras antes de consultar a explicação.</p></div>`;
 if(aiResult.explanation)return `<div class="spread"><h2>Vamos entender.</h2>${btn('Copiar','ai-copy','','quiet small')}</div><div class="ai-prose">${esc(aiResult.explanation)}</div><p class="form-help">Explicação gerada por IA. Confira regras, datas e referências no seu material.</p>`;
 if(aiResult.cards)return `<h2>Confira seus cartões.</h2><p>Edite as perguntas e respostas antes de adicionar à revisão.</p>${exam()?.subjects.some(s=>!s.archived)?`<form id="ai-save-form"><label>Salvar na matéria<select name="subjectId" required>${subjectOptions()}</select></label>${aiResult.cards.map((c,i)=>`<div class="ai-draft"><label class="checkbox-label"><input name="select-${i}" type="checkbox" ${c.saved?'disabled':'checked'}>Cartão ${i+1}${c.saved?' · Salvo':''}</label><label>Pergunta<textarea name="front-${i}" rows="2" maxlength="12000" ${c.saved?'readonly':''}>${esc(c.front)}</textarea></label><label>Resposta<textarea name="back-${i}" rows="3" maxlength="12000" ${c.saved?'readonly':''}>${esc(c.back)}</textarea></label></div>`).join('')}<button class="primary" ${aiResult.cards.every(c=>c.saved)?'disabled':''}>Adicionar selecionados aos cartões</button></form>`:`<div class="note">Crie uma preparação com pelo menos uma matéria para salvar cartões.</div>${aiResult.cards.map(c=>`<div class="ai-draft"><h3>${esc(c.front)}</h3><p>${esc(c.back)}</p></div>`).join('')}`}`;
 return `<h2>Recupere antes de conferir.</h2><p>Questões inéditas de treino geradas por IA. Estes resultados não entram nas estatísticas da sua preparação.</p>${aiResult.questions.map((q,i)=>`<fieldset class="ai-question"><legend>${i+1}. ${esc(q.prompt)}</legend>${q.options.map((o,j)=>`<label class="ai-option"><input type="radio" name="ai-q-${i}" value="${j}" ${q.revealed?'disabled':''} ${q.choice===j?'checked':''}>${esc(o)}</label>`).join('')}${q.revealed?`<div class="note ${q.choice===q.answer?'':'warn'}">${q.choice===q.answer?'Você acertou.':'Vamos revisar.'} Resposta: ${esc(q.options[q.answer])}<p>${esc(q.explanation)}</p></div>`:btn('Conferir resposta','ai-answer',`data-index="${i}"`,'small')}</fieldset>`).join('')}`;
}
let aiTurnstileLoading=null;
function aiLoadTurnstile(){
 if(window.turnstile)return Promise.resolve();
 if(aiTurnstileLoading)return aiTurnstileLoading;
 aiTurnstileLoading=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;script.onload=resolve;script.onerror=()=>{script.remove();aiTurnstileLoading=null;reject(Error('Não foi possível carregar a verificação. Confira sua conexão.'))};document.head.append(script)});return aiTurnstileLoading;
}
async function aiVerify(){
 const container=$('#ai-verification');if(!container||!$('#ai-form [name="consent"]')?.checked||!AI_ENDPOINT.startsWith('https://'))return;
 try{await aiLoadTurnstile();if(!container.isConnected||!$('#ai-form [name="consent"]')?.checked)return;aiToken='';if(aiWidget!==null){window.turnstile.remove(aiWidget);aiWidget=null}aiWidget=window.turnstile.render(container,{sitekey:AI_SITEKEY,action:'study',theme:db.theme,language:'pt-br',callback:token=>{aiToken=token;if($('#ai-security-status'))$('#ai-security-status').textContent='Verificação concluída.'},'expired-callback':()=>{aiToken='';if($('#ai-security-status'))$('#ai-security-status').textContent='Verificação expirada. Aguarde a renovação.'},'error-callback':()=>{aiToken='';if($('#ai-security-status'))$('#ai-security-status').textContent='A verificação falhou. Recarregue a página e tente novamente.'}})}catch(e){if($('#ai-security-status'))$('#ai-security-status').textContent=e.message}
}
function aiCleanupWidget(){if(aiWidget!==null&&window.turnstile){window.turnstile.remove(aiWidget);aiWidget=null}aiToken=''}
async function aiSubmit(form){
 if(aiBusy)return;if(tour)return toast('Envios à IA ficam desativados durante o tutorial.');
 const content=form.elements.content.value.trim();aiContent=form.elements.content.value;
 if(content.length<20||content.length>8000)return toast('Envie de 20 a 8.000 caracteres.');
 if(!form.elements.consent.checked)return toast('Confirme o envio deste texto para continuar.');
 if(!aiToken)return toast('Aguarde ou conclua a verificação de segurança.');
 const token=aiToken,mode=aiMode;aiExamId=exam()?.id||null;aiCleanupWidget();aiBusy=true;aiError='';aiResult=null;aiController=new AbortController();const timeout=setTimeout(()=>aiController?.abort(),60000);render();
 try{const response=await fetch(AI_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,content,token}),signal:aiController.signal});const data=await response.json();if(!response.ok)throw Error(data.error||'Não foi possível concluir o pedido.');if(!aiValidResult(mode,data.result))throw Error('A resposta não veio no formato esperado.');aiResult=data.result}
 catch(e){aiError=e.name==='AbortError'?'Pedido cancelado ou tempo de espera esgotado. Nenhum cartão foi salvo.':e.message==='Failed to fetch'?'Não foi possível conectar à IA. Confira sua internet e tente novamente.':e.message}
 finally{clearTimeout(timeout);aiBusy=false;aiController=null;if(route==='ia')render()}
}
function aiValidResult(mode,data){const text=x=>typeof x==='string'&&x.trim().length>0&&x.length<=12000;if(!data||typeof data!=='object')return false;if(mode==='explain')return text(data.explanation);if(mode==='cards')return Array.isArray(data.cards)&&data.cards.length===4&&data.cards.every(c=>c&&text(c.front)&&text(c.back));return Array.isArray(data.questions)&&data.questions.length===3&&data.questions.every(q=>q&&text(q.prompt)&&text(q.explanation)&&Array.isArray(q.options)&&q.options.length===4&&q.options.every(text)&&Number.isInteger(q.answer)&&q.answer>=0&&q.answer<4)}
Object.assign(actions,{
 'ai-mode':b=>{if(aiBusy)return;aiContent=$('#ai-content')?.value||aiContent;aiMode=b.dataset.mode;aiResult=null;aiError='';aiCleanupWidget();render()},
 'ai-cancel':()=>aiController?.abort(),
 'ai-copy':async()=>{try{await navigator.clipboard.writeText(aiResult.explanation);toast('Explicação copiada.')}catch{toast('Selecione a explicação para copiar.')}},
 'ai-answer':b=>{const i=+b.dataset.index,q=aiResult?.questions?.[i],choice=$(`input[name="ai-q-${i}"]:checked`);if(!q||!choice)return toast('Escolha uma alternativa antes de conferir.');q.choice=+choice.value;q.revealed=true;const field=b.closest('fieldset');field.insertAdjacentHTML('beforeend',`<div class="note ${q.choice===q.answer?'':'warn'}">${q.choice===q.answer?'Você acertou.':'Vamos revisar.'} Resposta: ${esc(q.options[q.answer])}<p>${esc(q.explanation)}</p></div>`);$$('input',field).forEach(x=>x.disabled=true);b.remove()},
 'ai-from-mistake':b=>{if(tour)return toast('A IA fica desativada durante a prática.');const m=exam()?.mistakes.find(x=>x.id===b.dataset.id);if(!m)return;aiMode='explain';aiResult=null;aiError='';aiContent=`Minha dificuldade: ${m.title}\nMinha explicação atual: ${m.explanation||''}`;go('ia')}
});
document.addEventListener('input',event=>{if(event.target.id==='ai-content'){aiContent=event.target.value;if($('#ai-length'))$('#ai-length').textContent=aiContent.length+'/8.000'}});
document.addEventListener('change',event=>{if(event.target.name==='consent'&&event.target.closest('#ai-form')){if(event.target.checked)aiVerify();else{aiCleanupWidget();if($('#ai-security-status'))$('#ai-security-status').textContent=''}}});
document.addEventListener('submit',event=>{
 if(event.target.id==='ai-form'){event.preventDefault();aiSubmit(event.target)}
 if(event.target.id==='ai-save-form'){
  event.preventDefault();if(tour)return toast('Saia do tutorial para salvar cartões.');const e=exam();if(!e||(aiExamId!==null&&aiExamId!==e.id))return toast('Volte à preparação em que os cartões foram gerados.');
  try{const d=new FormData(event.target),sid=d.get('subjectId');if(!e.subjects.some(s=>s.id===sid&&!s.archived))throw Error('Selecione uma matéria válida.');const selected=aiResult.cards.map((c,i)=>({c,i})).filter(({c,i})=>!c.saved&&d.has(`select-${i}`));if(!selected.length)throw Error('Selecione pelo menos um cartão.');const cards=selected.map(({c,i})=>{const front=String(d.get(`front-${i}`)||'').trim(),back=String(d.get(`back-${i}`)||'').trim();if(!front||!back||front.length>12000||back.length>12000)throw Error('Confira a pergunta e a resposta de cada cartão selecionado.');return {id:id(),subjectId:sid,topicId:null,front,back,due:today(),interval:0,reps:0,suspended:false}});snapshot();aiExamId=e.id;e.cards.push(...cards);selected.forEach(({c},i)=>{Object.assign(c,{front:cards[i].front,back:cards[i].back,saved:true,savedId:cards[i].id})});commit(`${cards.length} cartões adicionados à revisão.`,true)}catch(e){toast(e.message)}
 }
});
window.addEventListener('hashchange',()=>{if(route!=='ia')aiCleanupWidget()});
