let cardSpring=null,cardSpringFrame=0,cardMotionId=null;
function cardFaceState(){const card=$('.flashcard');if(!card)return;card.classList.toggle('answer',cardAnswer);card.setAttribute('aria-pressed',String(cardAnswer));const text=$('[data-face="'+(cardAnswer?'back':'front')+'"] h2',card)?.textContent||'';card.setAttribute('aria-label',(cardAnswer?'Resposta: ':'Pergunta: ')+text+(cardAnswer?'. Mostrar pergunta.':'. Revelar resposta.'));$$('.flashcard-face',card).forEach(face=>face.setAttribute('aria-hidden',String(face.dataset.face!==(cardAnswer?'back':'front'))));const ratings=$('.ratings');if(ratings)ratings.hidden=!cardAnswer}
function flipStudyCard(){cardAnswer=!cardAnswer;cardFaceState();const inner=$('.flashcard-inner');if(!inner)return;
 if(matchMedia('(prefers-reduced-motion: reduce)').matches){cancelAnimationFrame(cardSpringFrame);cardSpring=null;inner.style.transform=cardAnswer?'rotateY(180deg)':'rotateY(0deg)';return}
 if(!cardSpring||cardSpring.element!==inner)cardSpring={element:inner,value:cardAnswer?0:180,velocity:0,target:0,last:performance.now()};cardSpring.target=cardAnswer?180:0;
 if(!cardSpringFrame)cardSpringFrame=requestAnimationFrame(cardSpringStep);
}
function cardSpringStep(now){cardSpringFrame=0;const s=cardSpring;if(!s||!s.element.isConnected){cardSpring=null;return}const dt=Math.min(.025,(now-s.last)/1000);s.last=now;const force=(s.target-s.value)*380-s.velocity*39;s.velocity+=force*dt;s.value+=s.velocity*dt;s.element.style.transform='rotateY('+s.value+'deg)';if(Math.abs(s.target-s.value)<.08&&Math.abs(s.velocity)<.2){s.element.style.transform='rotateY('+s.target+'deg)';cardSpring=null}else cardSpringFrame=requestAnimationFrame(cardSpringStep)}
function syncCardMotion(){const inner=$('.flashcard-inner');if(cardSpring?.element!==inner){cancelAnimationFrame(cardSpringFrame);cardSpringFrame=0;cardSpring=null}if(!inner){cardMotionId=null;return}cardFaceState();inner.style.transform=cardAnswer?'rotateY(180deg)':'rotateY(0deg)';if(cardMotionId!==reviewCardId&&!matchMedia('(prefers-reduced-motion: reduce)').matches)inner.parentElement.animate([{opacity:.5,transform:'translateY(12px) scale(.985)'},{opacity:1,transform:'none'}],{duration:260,easing:'cubic-bezier(.2,.8,.2,1)'});cardMotionId=reviewCardId}
actions['card-flip']=flipStudyCard;
matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',()=>syncCardMotion());
