// Conversations belong to this browser and are included in the normal backup.
let aiActiveResultId=null,aiChatId=null,aiChatSearch='',aiChatListOpen=false,aiTourChat=false;
function aiCurrentChat(){return (db.aiChats||[]).find(c=>c.id===aiChatId&&c.examId===(exam()?.id||null))||null}
function aiChatSave(){if(!persist())toast('Não foi possível salvar a conversa. Exporte um backup para preservá-la.')}
function aiChatHistoryPayload(chat){
 const rows=[];let remaining=14000;
 for(const m of [...chat.messages].reverse()){
  if(m.error)continue;let text=m.role==='user'?m.content:m.result?.explanation||JSON.stringify(m.result);
  if(!text||remaining<=0)continue;text=text.slice(0,Math.min(4000,remaining));remaining-=text.length;rows.unshift({role:m.role,content:text});if(rows.length===12)break;
 }
 // A provider conversation must start with a student turn.
 while(rows[0]?.role==='assistant')rows.shift();return rows;
}
function aiChatBegin(content,mode){
 let chat=aiCurrentChat();db.aiChats??=[];
 if(!chat){if(db.aiChats.length>=60)throw Error('Você tem 60 conversas salvas. Exporte um backup e exclua uma para abrir espaço.');chat={id:id(),examId:exam()?.id||null,title:content.replace(/\s+/g,' ').slice(0,70),created:new Date().toISOString(),updated:new Date().toISOString(),messages:[]};db.aiChats.push(chat);aiChatId=chat.id}
 const previous=chat.messages.at(-1),retry=previous?.role==='user'&&previous.error&&previous.content===content;if(chat.messages.length+(retry?1:2)>100)throw Error('Este chat chegou a 100 mensagens. Comece outro para continuar.');
 if(JSON.stringify(db.aiChats).length+content.length+70000>2500000)throw Error('Seu histórico está grande. Exporte um backup e exclua conversas antigas antes de continuar.');
 const history=aiChatHistoryPayload(chat),last=chat.messages.at(-1);
 const message=last?.role==='user'&&last.error&&last.content===content?last:{id:id(),role:'user',content,mode};
 delete message.error;if(message!==last)chat.messages.push(message);chat.updated=new Date().toISOString();aiChatSave();return {chat,message,history};
}
function aiChatFinish(turn,result,error){if(!turn)return;const chat=(db.aiChats||[]).find(c=>c.id===turn.chat.id);if(!chat)return;if(error){const message=chat.messages.find(m=>m.id===turn.message.id);if(message)message.error=error;}else chat.messages.push({id:id(),role:'assistant',mode:turn.message.mode,result,questionCount:aiQuestionCount,difficulty:aiGeneratedDifficulty});chat.updated=new Date().toISOString();aiChatSave()}
function aiOpenChat(chatId){if(aiBusy)return toast('Cancele ou aguarde a resposta antes de trocar de chat.');const c=(db.aiChats||[]).find(c=>c.id===chatId&&c.examId===(exam()?.id||null));if(!c)return;aiCleanupWidget();aiChatId=c.id;aiChatListOpen=false;aiContent='';aiError='';const last=c.messages.findLast(m=>m.role==='assistant');aiResult=last?.result||null;aiExamId=c.examId;aiMode='explain';aiSubmittedContent=c.messages.findLast(m=>m.role==='user')?.content||'';aiQuizIndex=0;aiGeneratedDifficulty=last?.difficulty||'medium';render();aiFocusComposer()}
function aiChatThread(chat){return '<div class="norbit-thread" aria-label="Histórico da conversa">'+chat.messages.map((m,i)=>m.role==='user'?'<article class="norbit-user"><span class="norbit-message-label">Você</span><p>'+esc(m.content)+'</p>'+(m.error?'<p class="chat-error" role="alert">'+esc(m.error)+'</p>':'')+'</article>':'<section class="norbit-answer ai-output" tabindex="-1" aria-label="Resposta da NORBIT AI"><div class="norbit-answer-byline"><span class="norbit-symbol">'+norbitMark+'</span><strong>NORBIT AI</strong></div>'+ (m.result===aiResult&&!aiBusy&&!aiError?aiOutput():m.result.explanation?'<div class="ai-prose">'+esc(m.result.explanation)+'</div>':m.result.cards?m.result.cards.map(c=>'<details class="chat-saved-card"><summary>'+esc(c.front)+'</summary><p>'+esc(c.back)+'</p></details>').join(''):m.result.questions.map((q,n)=>'<details class="chat-saved-card"><summary>Questão '+(n+1)+' · '+esc(q.prompt)+'</summary><p>'+esc(q.explanation)+'</p></details>').join(''))+(m.result!==aiResult&&!m.result.explanation?btn(m.result.cards?'Revisar estes cartões':'Abrir este treino','chat-result','data-id="'+esc(m.id)+'"','secondary small'):'')+'</section>').join('')+(aiBusy?'<section class="ai-output norbit-answer" aria-busy="true">'+aiOutput()+'</section>':'')+'</div>'}
function aiChatSidebar(){const chats=(db.aiChats||[]).filter(c=>c.examId===(exam()?.id||null)).sort((a,b)=>b.updated.localeCompare(a.updated));return '<aside class="chat-sidebar '+(aiChatListOpen?'is-open':'')+'" aria-label="Conversas salvas"><div class="chat-sidebar-head"><strong>Suas conversas</strong>'+btn('＋ Nova','ai-new','','secondary small')+'</div><label class="chat-search">Buscar assunto<input id="chat-search" type="search" value="'+esc(aiChatSearch)+'" placeholder="Buscar conversa"></label><div class="chat-list">'+aiChatList(chats)+'</div><p class="chat-local-note">Salvas neste navegador, dentro do seu backup. Cada preparação tem suas conversas.</p></aside>'}
function aiChatList(chats=(db.aiChats||[]).filter(c=>c.examId===(exam()?.id||null)).sort((a,b)=>b.updated.localeCompare(a.updated))){return chats.filter(c=>c.title.toLocaleLowerCase().includes(aiChatSearch.toLocaleLowerCase())).map(c=>'<button class="chat-item '+(c.id===aiChatId?'active':'')+'" data-action="chat-open" data-id="'+esc(c.id)+'" '+(aiBusy?'disabled':'')+' aria-current="'+(c.id===aiChatId)+'"><strong>'+esc(c.title)+'</strong><small>'+c.messages.filter(m=>m.role==='user').length+' mensagens · '+new Date(c.updated).toLocaleDateString('pt-BR')+'</small></button>').join('')||'<p class="chat-list-empty">'+(aiChatSearch?'Nenhuma conversa encontrada.':'Sua primeira dúvida começa um chat.')+'</p>'}
function viewAI(){if(tour&&!aiTourChat)return viewAITools();const chat=aiCurrentChat();if(chat&&aiResult){const selected=chat.messages.find(m=>m.result===aiResult)||chat.messages.find(m=>m.id===aiActiveResultId);if(selected){aiResult=selected.result;aiActiveResultId=selected.id}}let html=viewAITools();if(chat?.messages.length){const start=html.indexOf('<div class="norbit-thread">'),end=html.indexOf('<div class="norbit-compose-wrap">');if(start>=0)html=html.slice(0,start)+aiChatThread(chat)+html.slice(end);else{const welcome=html.indexOf('<section class="norbit-welcome">');html=html.slice(0,welcome)+aiChatThread(chat)+html.slice(end)}}
 const controls=btn('Conversas','chat-list-toggle','','quiet small')+(chat?btn('Renomear','chat-rename','','quiet small')+btn('Excluir','chat-delete','','quiet small'):'');html=html.replace('</header>', '<div class="chat-tools">'+controls+'</div></header>');
 html=html.replace('minlength="20"','minlength="'+(chat?.messages.length?1:20)+'"').replace('Autorizo enviar este texto','Autorizo enviar o histórico recente deste chat e este texto').replace('A conversa fica apenas nesta sessão.','As conversas ficam salvas neste navegador e entram no backup. Para continuar, o histórico recente deste chat é enviado com sua mensagem. Até 12 mensagens recentes são usadas; conversas muito longas podem perder detalhes antigos.').replace('Só o texto escolhido é enviado.','Texto e histórico recente deste chat são enviados.');
 return '<div class="chat-workspace">'+aiChatSidebar()+'<div class="chat-main">'+html+'</div></div>';
}
const aiOriginalNew=actions['ai-new'];actions['ai-new']=()=>{if(aiBusy)return toast('Cancele ou aguarde o pedido atual.');aiChatId=null;aiActiveResultId=null;aiChatListOpen=false;aiOriginalNew()};
Object.assign(actions,{
 'chat-open':b=>aiOpenChat(b.dataset.id),
 'chat-result':b=>{if(aiBusy)return;const c=aiCurrentChat(),m=c?.messages.find(m=>m.id===b.dataset.id&&m.role==='assistant');if(!m)return;aiResult=m.result;aiExamId=c.examId;aiGeneratedDifficulty=m.difficulty||'medium';aiQuizIndex=0;aiError='';aiCleanupWidget();render()},
 'chat-list-toggle':()=>{aiChatListOpen=!aiChatListOpen;render()},
 'chat-rename':()=>{const c=aiCurrentChat();if(!c||aiBusy||tour)return;modal('Nome da conversa','Use o assunto para encontrar esta dúvida depois.','<label>Nome<input name="title" maxlength="100" required value="'+esc(c.title)+'"></label>','Salvar nome',d=>{if(!d.title.trim())throw Error('Informe um nome.');snapshot();c.title=d.title.trim();closeModal();commit('Conversa renomeada.',true)})},
 'chat-delete':()=>{const c=aiCurrentChat();if(!c||aiBusy||tour)return;confirmDialog('Excluir esta conversa?','As mensagens deste chat serão removidas deste navegador.',()=>{snapshot();db.aiChats=db.aiChats.filter(x=>x.id!==c.id);closeModal();actions['ai-new']();commit('Conversa excluída.',true)},'Excluir conversa')}
});
document.addEventListener('input',e=>{if(e.target.id==='chat-search'){aiChatSearch=e.target.value;$('.chat-list').innerHTML=aiChatList()}});

function studyChatDemo(){aiTourChat=true;aiChatListOpen=true;aiChatSearch='';const chat={id:id(),examId:exam().id,title:'Recuperação ativa',created:new Date().toISOString(),updated:new Date().toISOString(),messages:[{id:id(),role:'user',mode:'explain',content:'O que significa recuperação ativa nos estudos?'},{id:id(),role:'assistant',mode:'explain',result:{explanation:'É tentar lembrar antes de consultar. Você tentaria explicar o conteúdo com o material fechado?'}},{id:id(),role:'user',mode:'explain',content:'Sim, eu fecharia o material antes de explicar.'},{id:id(),role:'assistant',mode:'explain',result:{explanation:'Isso mesmo. Sua resposta aplica a recuperação ativa. Depois de tentar, confira o material e corrija o que faltou. DEMONSTRAÇÃO LOCAL: não houve envio à IA.'}}]};db.aiChats=[chat];aiChatId=chat.id;aiResult=chat.messages.at(-1).result;aiSubmittedContent=chat.messages.at(-2).content;aiContent='';aiError='';aiMode='explain';render()}
tourAreas.ia.steps.push(tStep('.chat-sidebar','Cada dúvida tem sua conversa.','As conversas ficam organizadas por assunto e preparação. No celular, toque em Conversas para abrir a lista. Estamos usando um histórico temporário.',{prepare:studyChatDemo}),tStep('#chat-search','Encontre o assunto depois.','Busque pelo nome, reabra uma conversa e continue de onde parou. Os chats ficam salvos neste navegador e entram no backup.'),tStep('.norbit-thread','A resposta acompanha o raciocínio.','Veja o exemplo: o tutor fez uma pergunta, o aluno respondeu e a conversa continuou com feedback. Cada envio usa até 12 mensagens recentes do mesmo chat.'),tStep('.chat-tools','Um nome que faça sentido.','Renomeie pelo assunto, comece outra conversa ou exclua uma que não precisa mais. Excluir permite desfazer; exportar backup preserva seu histórico.'));
