/* Connected learning remains local; suggestions never register study automatically. */
function connected(e=exam()){return e?.studio?.connected||{notebooks:[],reviews:{},reports:[],guided:null}}
function writeConnected(e=exam()){return writeStudio(e).connected??=connected(e)}
const validateBeforeConnected=validateBackup;
validateBackup=function(data){validateBeforeConnected(data);for(const e of data.exams){const d=e.studio?.connected;if(!d)continue;if(!Array.isArray(d.notebooks)||d.notebooks.length>100||d.notebooks.some(n=>!n||typeof n.id!=='string'||n.id.length>150||typeof n.name!=='string'||!n.name.trim()||n.name.length>100)||new Set(d.notebooks.map(n=>n.id)).size!==d.notebooks.length||!d.reviews||typeof d.reviews!=='object'||Array.isArray(d.reviews)||Object.keys(d.reviews).length>500||Object.values(d.reviews).some(r=>!validDate(r.due)||!Number.isInteger(r.interval)||!num(r.interval,1,180))||!Array.isArray(d.reports)||d.reports.length>100||d.reports.some(r=>!r||typeof r.id!=='string'||typeof r.reason!=='string'||r.reason.length>2000||!validDate(r.date)))throw Error('Os dados conectados do backup estão inválidos.');const g=d.guided;if(g&&(!subjectIn(e,g.sid,g.tid)||!Number.isInteger(g.step)||!num(g.step,0,4)||typeof g.recall!=='string'||g.recall.length>12000||typeof g.reflection!=='string'||g.reflection.length>12000||!Array.isArray(g.questions)||g.questions.length>5||g.questions.some(q=>!validBankQuestion(q))||!Array.isArray(g.choices)||g.choices.length!==g.questions.length||!Number.isFinite(g.startedAt)||!Array.isArray(g.grades)||g.grades.some(v=>v!==null&&v!==0&&v!==1)))throw Error('A sessão guiada está inválida.')}return true};
function subjectIn(e,sid,tid){return e.subjects.some(s=>s.id===sid&&(!tid||s.topics.some(t=>t.id===tid)))}
sidebarGroups[1][1]=sidebarGroups[1][1].filter(key=>!['questoes','simulados'].includes(key));
routes.find(r=>r[0]==='banco')[1]='Praticar';
function practiceNavigation(){return `<nav class="practice-subnav" aria-label="Áreas de prática">${[['banco','Banco de questões'],['questoes','Questões e erros'],['simulados','Simulados']].map(([key,label])=>`<a href="#${key}" aria-current="${route===key?'page':'false'}">${esc(label)}</a>`).join('')}</nav>`}
const questionsBeforeConnected=viewQuestions;viewQuestions=function(){return practiceNavigation()+questionsBeforeConnected()};const mocksBeforeConnected=viewMocks;viewMocks=function(){return practiceNavigation()+mocksBeforeConnected()};
routes.push(['jornada','Sessão guiada']);
function startGuided(){if(connected().guided)return go('jornada');if(!exam()?.subjects.some(s=>!s.archived))return toast('Adicione uma matéria e um assunto primeiro.');modal('Seu próximo bloco de estudo','Lembrar, praticar, conferir e escolher o próximo passo.',`<div class="form-grid">${selection(studySubjectId,studyTopicId)}<label>Tempo disponível<select name="minutes">${[10,15,25,45].map(n=>`<option ${n===25?'selected':''}>${n}</option>`).join('')}</select></label></div>`,'Começar sessão',d=>{if(!subject(d.subjectId)||!topic(d.subjectId,d.topicId))throw Error('Escolha uma matéria e um assunto.');const questions=studio().bank.filter(q=>q.subjectId===d.subjectId&&q.topicId===d.topicId).slice(0,5);writeConnected().guided={id:id(),sid:d.subjectId,tid:d.topicId,step:0,minutes:+d.minutes,startedAt:Date.now(),recall:'',reflection:'',questions:clone(questions),choices:questions.map(()=>null),grades:questions.map(()=>null)};persist();closeModal();go('jornada')})}
function viewGuidedStudy(){const g=connected().guided;if(!g)return heading('Um assunto. Um caminho completo.','Tente lembrar, pratique e termine com um próximo passo.',btn('Começar sessão guiada','guided-start','','primary'));const t=topic(g.sid,g.tid),labels=['Escolher','Lembrar','Praticar','Conferir','Registrar'];return heading(esc(t?.name||'Sessão guiada'),esc(subjectName(g.sid))+' · '+g.minutes+' minutos disponíveis',btn('Guardar e sair','navigate','data-route="hoje"','quiet'))+`<section class="panel guided-sheet"><ol class="guided-track">${labels.map((label,i)=>`<li aria-current="${i===g.step?'step':'false'}"><span>${i+1}</span>${label}</li>`).join('')}</ol><div id="guided-stage">${g.step===0?`<h2>Comece com uma pergunta.</h2><p>O que você gostaria de conseguir explicar sobre ${esc(t?.name||'este assunto')} ao terminar?</p><p class="form-help">A sessão fica salva se você sair. Nenhum resultado é registrado antes da confirmação final.</p>`:g.step===1?`<h2>Primeiro, tente lembrar.</h2><label>Explique sem consultar<textarea id="guided-recall" maxlength="12000" rows="7">${esc(g.recall)}</textarea></label><p class="form-help">Estas palavras ficam neste aparelho e não são enviadas à IA.</p>`:g.step===2?`<h2>Coloque a ideia em prática.</h2>${g.questions.length?g.questions.map((q,i)=>`<fieldset class="guided-question"><legend>${i+1}. ${esc(q.prompt)}</legend>${questionInput(q,g.choices[i],'guided-answer-'+i,`data-guided-index="${i}"`)}</fieldset>`).join(''):'<p>Não há perguntas deste assunto no banco. Use seu material para fazer uma pergunta e escreva o resultado no próximo passo.</p>'}`:g.step===3?`<h2>Confira e ajuste.</h2>${g.questions.map((q,i)=>`<section class="guided-correction"><h3>${i+1}. ${esc(q.prompt)}</h3><p>Sua resposta: ${esc(choiceLabel(q,g.choices[i]))}</p><p>Referência: ${esc(answerLabel(q))}</p><p>${esc(q.explanation)}</p>${q.type==='essay'?`<label>Autoavaliação pelo critério<select data-guided-grade="${i}"><option value="">Ainda não avaliei</option><option value="1" ${g.grades[i]===1?'selected':''}>Atendi ao critério</option><option value="0" ${g.grades[i]===0?'selected':''}>Preciso retomar</option></select></label>`:''}</section>`).join('')}<label>O que faltou? O que quero retomar?<textarea id="guided-reflection" maxlength="12000" rows="4">${esc(g.reflection)}</textarea></label>`:`<h2>Transforme o bloco em um próximo passo.</h2><p>Confira os minutos reais e os resultados no formulário. A sessão só entra no histórico uma vez.</p><div class="actions">${btn('Registrar esta sessão','guided-register','','primary')}${btn('Revisar o assunto amanhã','guided-review','','secondary')}${btn('Criar cartão do que faltou','guided-card','','quiet')}</div>`}</div><div class="guided-navigation">${btn('Anterior','guided-step',`data-step="${g.step-1}" ${g.step===0?'disabled':''}`,'quiet small')}${g.step<4?btn('Continuar','guided-step',`data-step="${g.step+1}"`,'primary small'):''}</div></section>`}
function guidedSaveInputs(){const g=connected().guided;if(!g)return;if($('#guided-recall'))g.recall=$('#guided-recall').value;if($('#guided-reflection'))g.reflection=$('#guided-reflection').value;persist()}
document.addEventListener('input',event=>{if(['guided-recall','guided-reflection'].includes(event.target.id))guidedSaveInputs();if(event.target.dataset.guidedIndex!==undefined){const g=connected().guided;if(g){g.choices[+event.target.dataset.guidedIndex]=event.target.type==='radio'?+event.target.value:event.target.value;persist()}}});
document.addEventListener('change',event=>{if(event.target.dataset.guidedGrade!==undefined){connected().guided.grades[+event.target.dataset.guidedGrade]=event.target.value===''?null:+event.target.value;persist()}});
const todayBeforeConnected=viewPersonalToday;viewPersonalToday=function(){return `<section class="panel connected-start" id="connected-start"><div><span class="tag blue">ESTUDAR AGORA</span><h2>Aprender, do começo ao próximo passo.</h2><p>Uma sessão reúne lembrança, questões e revisão.</p></div>${btn(connected().guided?'Retomar sessão guiada':'Começar sessão guiada','guided-start','','primary')}</section>`+todayBeforeConnected()};
Object.assign(actions,{
 'guided-start':startGuided,'guided-step':b=>{guidedSaveInputs();const g=connected().guided,step=+b.dataset.step;if(g&&Number.isInteger(step)&&num(step,0,4)){g.step=step;persist();render();$('#guided-stage h2')?.scrollIntoView({block:'nearest'})}},
 'guided-register':()=>{guidedSaveInputs();const g=connected().guided;if(!g)return;if(g.questions.some((q,i)=>q.type==='essay'&&g.choices[i]&&g.grades[i]===null))return toast('Confira as respostas discursivas antes de registrar.');sessionForm({sid:g.sid,tid:g.tid,type:'Questões',minutes:Math.min(1440,Math.max(1,Math.round((Date.now()-g.startedAt)/60000)))});const f=$('#modal-form');f.elements.qty.value=g.questions.length;f.elements.correct.value=g.questions.filter((q,i)=>questionCorrect(q,g.choices[i],g.grades[i])).length;f.elements.notes.value=('Lembrança: '+g.recall+'\nRetomar: '+g.reflection).slice(0,12000);const save=f.onsubmit;f.onsubmit=event=>{const before=exam().sessions.length;save(event);if(exam().sessions.length===before)return;const record=exam().sessions.at(-1);record.source='guided';if(g.questions.length&&studio().attempts.length<100)writeStudio().attempts.push({id:g.id,title:'Sessão guiada: '+topicName(g.sid,g.tid),date:record.date,minutes:record.minutes,questions:clone(g.questions),choices:clone(g.choices),grades:clone(g.grades),sessionIds:[record.id]});writeConnected().guided=null;persist();render()}},
 'guided-review':()=>{const g=connected().guided,t=g&&topic(g.sid,g.tid);if(t){snapshot();t.nextReview=addDays(today(),1);commit('Revisão marcada para amanhã.',true)}},
 'guided-card':()=>{const g=connected().guided;if(g)openCard(null,{subjectId:g.sid,topicId:g.tid,front:'Como explicar '+topicName(g.sid,g.tid)+'?',back:g.reflection||g.recall})}
});
// Save drafts without remounting the textarea. Flush before navigation.
let notePending=null,noteSaveTimer=null;
function flushNote(){clearTimeout(noteSaveTimer);const pending=notePending;if(!pending)return;notePending=null;const e=db.exams.find(e=>e.id===pending.examId);if(!e)return;const d=writeStudio(e),previous=d.notes[pending.key];d.notes[pending.key]=pending.value;try{if(JSON.stringify(d).length>1500000)throw Error('Sem espaço');if(!persist())throw Error('Não foi possível salvar');const status=$('#notes-save-status');if(status)status.textContent='Salvo neste aparelho'}catch{if(previous===undefined)delete d.notes[pending.key];else d.notes[pending.key]=previous;notePending=pending;const status=$('#notes-save-status');if(status)status.textContent='Não foi possível salvar. Copie sua anotação antes de sair.'}}
document.addEventListener('input',event=>{const form=event.target.closest('#topic-notes,#focus-notes');if(!form||event.target.name!=='notes'||!exam())return;const key=form.id==='topic-notes'?studyTopicId:form.dataset.key;if(!key)return;notePending={examId:exam().id,key,value:event.target.value.slice(0,12000)};let status=$('#notes-save-status');if(!status){status=document.createElement('p');status.id='notes-save-status';status.className='form-help';status.setAttribute('role','status');form.append(status)}status.textContent='Salvando…';clearTimeout(noteSaveTimer);noteSaveTimer=setTimeout(flushNote,400)});
document.addEventListener('click',event=>{if(event.target.closest('a[href^="#"],[data-action]')&&notePending)flushNote()},true);window.addEventListener('beforeunload',flushNote);document.addEventListener('visibilitychange',()=>{if(document.hidden)flushNote()});
const topicHubBeforeConnected=topicHub;topicHub=function(){return topicHubBeforeConnected().replace('Notas locais, enviadas à IA apenas quando selecionadas.','Notas salvas automaticamente neste aparelho. Envie à IA somente quando escolher.')};
// One local restore point supplements, but never replaces, the manual export.
const persistBeforeConnected=persist;let restorePointAttempt=0;persist=function(){const saved=persistBeforeConnected();if(saved&&!tour&&Date.now()-restorePointAttempt>3600000){restorePointAttempt=Date.now();try{const key=STORE+'.restore-point',old=JSON.parse(localStorage.getItem(key)||'null'),json=JSON.stringify(db);if(json.length<=750000&&(!old||Date.now()-old.created>86400000))localStorage.setItem(key,JSON.stringify({created:Date.now(),data:clone(db)}))}catch{}}return saved};
const settingsBeforeConnected=viewSettings;viewSettings=function(){return settingsBeforeConnected()+`<section class="panel subsection">${panelHead('Recuperação neste aparelho','Uma cópia local diária pode ajudar após uma edição. Ela não protege contra limpar o navegador.')}<div class="actions">${btn('Conferir cópia local','local-restore','','secondary small')}${btn('Exportar backup completo','export','','primary small')}</div></section>`};
actions['local-restore']=()=>{let point;try{point=JSON.parse(localStorage.getItem(STORE+'.restore-point')||'null');if(point)validateBackup(point.data)}catch{return toast('A cópia local não pôde ser validada. Use seu backup manual.')}if(!point)return toast('Ainda não há uma cópia local disponível.');modal('Conferir antes de restaurar','Cópia de '+new Date(point.created).toLocaleString('pt-BR'),`<p>${point.data.exams.length} preparações. Restaurar substitui os dados atuais neste navegador.</p><p>Exporte o backup atual antes de continuar. Você poderá desfazer esta restauração.</p>`,'Restaurar cópia',()=>{snapshot();db=clone(point.data);closeModal();go('hoje');commit('Cópia local restaurada. Você pode desfazer.',true)})};
