// Guided onboarding runs locally. Sending a study profile to AI requires the context switch and consent.
const NORBIT_MASCOT='__NORBIT_MASCOT__';
const studyKinds={concurso:{label:'Concurso',description:'Edital, questões e preparação para a prova.',syllabus:'Meu edital',date:'Data da prova',title:'Concurso ou objetivo',placeholder:'Ex.: Concurso administrativo'},faculdade:{label:'Faculdade',description:'Disciplinas, provas, trabalhos e semestre.',syllabus:'Minhas disciplinas',date:'Fim do semestre (opcional)',title:'Nome deste espaço',placeholder:'Ex.: Administração · 2º semestre'},escola:{label:'Escola e vestibular',description:'Matérias, revisões e preparação para avaliações.',syllabus:'Minhas matérias',date:'Data-alvo (opcional)',title:'Objetivo de estudo',placeholder:'Ex.: Ensino médio · ENEM'},certificacao:{label:'Cursos e certificações',description:'Uma trilha para aprender e praticar.',syllabus:'Minha trilha',date:'Data-alvo (opcional)',title:'Curso ou certificação',placeholder:'Ex.: Certificação em redes'},livre:{label:'Aprender por conta própria',description:'Projetos, idiomas e interesses pessoais.',syllabus:'Minha trilha',date:'Data-alvo (opcional)',title:'O que você quer aprender?',placeholder:'Ex.: Aprender inglês'}};
const studyRoles={estudante:'Estudante',profissional:'Profissional',ambos:'Estudo e trabalho',outro:'Outro momento'};
const studyLevels={inicio:'Começando',intermediario:'Já tenho uma base',avancado:'Quero aprofundar'};
const studyChallenges={constancia:'Manter a constância',tempo:'Encontrar tempo',compreensao:'Entender o conteúdo',memoria:'Lembrar depois',pratica:'Aplicar o que aprendo'};
const studyMethods={explicacao:'Entender com exemplos',cartoes:'Revisar com cartões',questoes:'Praticar questões'};
let profileDraft=null,profileStep=0,profileEditingId=null;
function studyKind(e=exam()){return e?.learningProfile?.kind||'concurso'}
function studyLabel(key,e=exam()){const kind=studyKinds[studyKind(e)];return key==='edital'?kind.syllabus:key==='simulados'&&studyKind(e)!=='concurso'?'Avaliações de prática':routes.find(r=>r[0]===key)?.[1]||key}
function norbitMascot(state='welcome',size='small'){return `<span class="norbit-mascot mascot-${size}" data-state="${state}" aria-hidden="true"><img src="${NORBIT_MASCOT}" alt="" width="512" height="512"><i class="mascot-spark"></i></span>`}
function studyAdvice(p=exam()?.learningProfile){if(!p)return 'Escolha um objetivo e vamos ajustar seu espaço de estudos.';return ({constancia:'Comece com um bloco possível de repetir. O progresso vem da rotina.',tempo:'Proteja os horários que você escolheu. Um bloco curto também conta.',compreensao:'Explique com suas palavras e peça exemplos antes de avançar.',memoria:'Tente lembrar sem consultar. Depois revise com cartões e espaçamento.',pratica:'Alterne explicação e aplicação. Corrija os erros antes de repetir.'})[p.challenge]}
function profileBegin(edit=false,navigate=true){if(tour&&edit===false)return toast('Crie um espaço fora do tutorial.');const e=edit?exam():null,p=e?.learningProfile,a=e?.availability.find(a=>a.enabled);profileEditingId=e?.id||null;profileStep=0;profileDraft={kind:p?.kind||'',role:p?.role||'',course:p?.course||'',term:p?.term||'',level:p?.level||'inicio',challenge:p?.challenge||'constancia',method:p?.method||'explicacao',name:db.name==='Estudante'?'':db.name,goal:e?.name||'',position:e?.position||'',board:e?.board||'',date:e?.date||'',subjects:'',minutes:e?.dailyMinutes||60,questions:e?.dailyQuestions||10,block:e?.blockMinutes||25,start:a?.start||'19:00',days:e?e.availability.filter(a=>a.enabled).map(a=>a.day):[1,3,5],applyRoutine:!e,createPlan:!e};if(navigate){closeModal();go('perfil')}}
function profileEnsure(){if(!profileDraft&&exam())profileBegin(true,false);if(!profileDraft)profileDraft={kind:'',role:'',course:'',term:'',level:'inicio',challenge:'constancia',method:'explicacao',name:'',goal:'',position:'',board:'',date:'',subjects:'',minutes:60,questions:10,block:25,start:'19:00',days:[1,3,5],applyRoutine:true,createPlan:true}}
function profileField(name,label,options={}){const {type='text',required=false,max=120,placeholder=''}=options;return `<label>${label}<input id="profile-${name}" name="${name}" type="${type}" value="${esc(profileDraft[name])}" ${required?'required':''} ${type==='text'?`maxlength="${max}"`:''} placeholder="${esc(placeholder)}"></label>`}
function profileSelect(name,label,items){return `<label>${label}<select name="${name}" id="profile-${name}">${Object.entries(items).map(([value,text])=>`<option value="${value}" ${profileDraft[name]===value?'selected':''}>${esc(text)}</option>`).join('')}</select></label>`}
function viewProfile(){profileEnsure();const d=profileDraft,kind=studyKinds[d.kind],editing=!!profileEditingId,titles=['Seu estudo tem um destino.','Quero conhecer o seu momento.','O que vamos estudar?','Vamos montar uma rotina possível.','Este espaço tem a sua cara.'];const descriptions=['Sou a NORBIT. Vou fazer algumas perguntas para organizar o Norte ao seu redor.','Conte apenas o que ajudar a orientar seus estudos. Você pode mudar isso depois.','Use os nomes das suas disciplinas, matérias ou temas. Você completa os assuntos depois.','Escolha dias e horários reais. A primeira semana vai respeitar esse espaço.','Confira suas escolhas antes de salvar. Nada foi alterado até aqui.'];let fields='';
 if(profileStep===0)fields=`<div class="profile-choices" role="group" aria-label="Objetivo de estudo">${Object.entries(studyKinds).map(([key,value],i)=>`<button type="button" data-action="profile-kind" data-profile-kind="${key}" aria-pressed="${d.kind===key}"><span class="profile-choice-index">0${i+1}</span><span><strong>${value.label}</strong><small>${value.description}</small></span><span aria-hidden="true">↗</span></button>`).join('')}</div>`;
 if(profileStep===1)fields=`<div class="form-grid">${profileField('name','Como quer ser chamado?',{max:80,placeholder:'Opcional'})}${profileSelect('role','Qual é o seu momento?',{'':'Escolha uma opção',...studyRoles})}${profileField('goal',kind.title,{required:true,placeholder:kind.placeholder})}${profileField('course',d.kind==='faculdade'?'Qual curso você faz?':'Curso ou área de interesse',{required:d.kind==='faculdade',placeholder:d.kind==='faculdade'?'Ex.: Engenharia de Software':'Opcional'})}${profileField('term',d.kind==='faculdade'?'Semestre ou período':'Etapa atual',{max:60,placeholder:'Opcional'})}${profileField('date',kind.date,{type:'date'})}${d.kind==='concurso'?profileField('position','Cargo desejado',{max:150,placeholder:'Opcional'})+profileField('board','Banca',{placeholder:'Opcional'}):''}</div>`;
 if(profileStep===2)fields=`<label>${editing?'Adicionar novas disciplinas ou temas (opcional)':'Disciplinas, matérias ou temas'}<textarea id="profile-subjects" name="subjects" rows="5" maxlength="5000" placeholder="Um por linha. Ex.:\nCálculo I\nProgramação\nEstatística">${esc(d.subjects)}</textarea></label><p class="form-help">${editing?'As matérias e os registros existentes serão preservados. Novos nomes serão adicionados sem repetir os atuais.':'Você pode deixar em branco e cadastrar depois. Para os nomes informados, criaremos um tópico geral; personalize-o com seu conteúdo real.'}</p><div class="form-grid">${profileSelect('level','Como está sua base?',studyLevels)}${profileSelect('challenge','Onde você mais precisa de ajuda?',studyChallenges)}${profileSelect('method','Por onde prefere começar?',studyMethods)}</div>`;
 if(profileStep===3)fields=`<div id="profile-routine">${editing?`<label class="checkbox-label"><input name="applyRoutine" type="checkbox" ${d.applyRoutine?'checked':''}>Aplicar esta nova rotina às metas e horários</label><p class="form-help">Sem marcar, seus horários e metas atuais continuam iguais. Atividades já planejadas nunca são substituídas aqui.</p>`:''}<div class="form-grid">${profileSelect('minutes','Minutos em cada dia de estudo',{30:'30 minutos',60:'1 hora',90:'1h30',120:'2 horas',180:'3 horas'})}${profileField('start','Horário de início',{type:'time',required:true})}${profileSelect('block','Tamanho dos blocos',{25:'25 minutos',30:'30 minutos',45:'45 minutos',50:'50 minutos'})}<label>Questões por dia de estudo<input name="questions" id="profile-questions" type="number" min="1" max="5000" step="1" required value="${d.questions}"></label></div><fieldset class="profile-days"><legend>Em quais dias você pode estudar?</legend>${['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map((day,i)=>`<label><input name="day" type="checkbox" value="${i}" ${d.days.includes(i)?'checked':''}><span>${day}</span></label>`).join('')}</fieldset><p class="form-help">${kind.date} limita a geração do plano quando informada. Provas e entregas específicas podem ser cadastradas no painel.</p></div>`;
 if(profileStep===4){const existing=db.exams.find(e=>e.id===profileEditingId),apply=!editing||d.applyRoutine,minutes=apply?+d.minutes:existing.dailyMinutes,weekly=apply?minutes*d.days.length:existing.weeklyMinutes;fields=`<div class="profile-review"><span>${tag(kind.label,'blue')}</span><h2>${esc(d.goal)}</h2><p>${esc([d.course,d.term].filter(Boolean).join(' · ')||studyRoles[d.role])}</p><dl><div><dt>Seu momento</dt><dd>${esc(studyRoles[d.role])}</dd></div><div><dt>Tempo de estudo</dt><dd>${minutesLabel(minutes)} por dia · ${minutesLabel(weekly)} por semana</dd></div><div><dt>Ponto de partida</dt><dd>${esc(studyLevels[d.level])}</dd></div><div><dt>Vamos reforçar</dt><dd>${esc(studyChallenges[d.challenge])}</dd></div></dl><div class="profile-advice">${norbitMascot('success','tiny')}<p>${esc(studyAdvice(d))}</p></div></div>${!editing?`<label class="checkbox-label"><input type="checkbox" name="createPlan" ${d.createPlan?'checked':''}>Criar a primeira semana com as matérias informadas</label><p class="form-help">A sugestão usa os próximos 7 dias, com pausas de 5 minutos. Confira e ajuste em Planejamento.</p>`:'<p class="form-help">Seus registros, cartões, materiais e planos existentes serão preservados.</p>'}`}
 return `<section class="profile-page"><header class="profile-header"><div class="norbit-identity"><span class="norbit-symbol">${norbitMark}</span><span><strong>NORBIT <span>AI</span></strong><small>Vamos encontrar o seu norte.</small></span></div><div class="actions">${btn('Tutorial','profile-tour','','quiet small')}${btn(editing?'Cancelar edição':exam()?'Voltar ao painel':'Explorar exemplo',exam()?'profile-cancel':'demo','','quiet small')}</div></header><div class="profile-layout"><aside class="profile-companion">${norbitMascot(profileStep===4?'success':profileStep===3?'focus':'welcome','hero')}<span class="profile-kicker">UM ESPAÇO PARA O SEU MOMENTO</span><p>${profileStep===4?'Tudo pronto para começar.':'Você traz o objetivo. Eu ajudo a organizar os próximos passos.'}</p><small>Conversa guiada no aparelho.<br>Sem usar sua cota de IA.</small></aside><div class="profile-conversation"><div class="profile-progress" aria-label="Etapa ${profileStep+1} de 5">${Array.from({length:5},(_,i)=>`<span class="${i<=profileStep?'active':''}"></span>`).join('')}</div><p class="profile-step">${editing?'Ajustar meu espaço':'Conhecer você'} · ${profileStep+1} de 5</p><h1 tabindex="-1" id="profile-heading">${titles[profileStep]}</h1><p class="profile-description">${descriptions[profileStep]}</p><form id="profile-wizard">${fields}<p id="profile-error" class="form-error" role="alert"></p><div class="profile-controls">${profileStep?btn('Voltar','profile-back','','quiet'):''}${profileStep?`<button class="primary" type="submit">${profileStep===4?editing?'Salvar meu perfil':'Criar meu espaço':'Continuar'} <span aria-hidden="true">↗</span></button>`:''}</div></form><p class="profile-local">Seu perfil fica neste navegador. O envio ao assistente depende da opção de contexto e da sua autorização.</p>${!exam()?`<div class="actions profile-explore">${btn('Conhecer com dados de exemplo','demo','','quiet small')}${btn('Ver tutorial','guide-open','','quiet small')}</div>`:''}</div></div></section>`;
}
function profileRead(form){const values=new FormData(form),d=profileDraft;for(const key of ['name','role','goal','course','term','date','position','board','subjects','level','challenge','method','start'])if(values.has(key))d[key]=String(values.get(key)).trim();for(const key of ['minutes','questions','block'])if(values.has(key))d[key]=Number(values.get(key));if(profileStep===3){d.days=values.getAll('day').map(Number);d.applyRoutine=profileEditingId?values.get('applyRoutine')==='on':true}if(profileStep===4&&!profileEditingId)d.createPlan=values.get('createPlan')==='on'}
function profileValidateStep(){const d=profileDraft;if(profileStep===1){if(!studyRoles[d.role])throw Error('Escolha o seu momento.');if(!d.goal||d.goal.length>120)throw Error('Informe um objetivo de até 120 caracteres.');if(d.kind==='faculdade'&&!d.course)throw Error('Conte qual curso você faz.');if(d.date&&!validDate(d.date))throw Error('Confira a data informada.')}if(profileStep===2){const names=d.subjects.split(/\r?\n/).map(s=>s.trim()).filter(Boolean);if(names.length>30||names.some(s=>s.length>180))throw Error('Use até 30 disciplinas ou temas, com até 180 caracteres cada.')}if(profileStep===3&&d.applyRoutine){if(!d.days.length)throw Error('Escolha ao menos um dia de estudo.');if(!Number.isInteger(d.questions)||!num(d.questions,1,5000))throw Error('Escolha uma meta de questões entre 1 e 5000.');if(!num(d.minutes,30,180)||!num(d.block,25,50)||d.block>d.minutes)throw Error('O bloco precisa caber no tempo disponível.');if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(d.start)||timeMin(d.start)+d.minutes>1439)throw Error('Escolha um horário que termine antes da meia-noite.')}}
function profileFinish(){const d=profileDraft;const current=db.exams.find(e=>e.id===profileEditingId);if(profileEditingId&&!current)throw Error('Este espaço foi removido. Cancele e comece novamente.');const next=clone(db),e=current?next.exams.find(e=>e.id===current.id):newExam(d.goal);Object.assign(e,{name:d.goal,date:d.date,position:d.kind==='concurso'?d.position:'',board:d.kind==='concurso'?d.board:'',learningProfile:{kind:d.kind,role:d.role,course:d.course,term:d.term,level:d.level,challenge:d.challenge,method:d.method}});if(!current||d.applyRoutine){e.dailyMinutes=+d.minutes;e.dailyQuestions=+d.questions;e.weeklyMinutes=d.minutes*d.days.length;e.blockMinutes=+d.block;e.availability=Array.from({length:7},(_,day)=>({day,enabled:d.days.includes(day),start:d.start,end:hm(timeMin(d.start)+d.minutes)}))}const existing=new Set(e.subjects.map(s=>s.name.toLocaleLowerCase('pt-BR')));for(const name of d.subjects.split(/\r?\n/).map(s=>s.trim()).filter(Boolean)){const key=name.toLocaleLowerCase('pt-BR');if(existing.has(key))continue;e.subjects.push({id:id(),name,weight:3,archived:false,topics:makeTopics('Fundamentos e prática')});existing.add(key)}if(!current)next.exams.push(e);next.activeExam=e.id;if(d.name)next.name=d.name;validateBackup(next);snapshot();const previous=db;db=next;try{if(!current&&d.createPlan&&e.subjects.length)e.plans=generatePlan(e,today(),7,e.blockMinutes,e.availability,false);validateBackup(db)}catch(error){db=previous;throw error}if(!aiResult&&!aiBusy)aiMode=({explicacao:'explain',cartoes:'cards',questoes:'quiz'})[d.method];profileDraft=null;profileEditingId=null;profileStep=0;persist();go('hoje');toast(current?'Seu espaço foi adaptado. Os registros foram preservados.':'Seu espaço está pronto. Confira sua primeira semana.',true)}
function profileSummary(){const p=exam()?.learningProfile;if(tour)return '';if(!p)return `<section class="profile-banner"><div>${norbitMascot('welcome','small')}</div><div><h2>Qual é o seu próximo objetivo?</h2><p>A NORBIT pode adaptar este espaço à faculdade, a um concurso ou a uma nova habilidade.</p></div>${btn('Adaptar meu espaço','profile-edit','','secondary small')}</section>`;return `<section class="profile-banner"><div>${norbitMascot('welcome','small')}</div><div><span class="profile-kicker">${esc(studyKinds[p.kind].label)}</span><h2>${esc(p.course||exam().name)}${p.term?` · ${esc(p.term)}`:''}</h2><p>${esc(studyAdvice(p))}</p></div>${btn('Ajustar meu perfil','profile-edit','','quiet small')}</section>`}
function studyTasks(e=exam()){return (e?.studyTasks||[]).filter(t=>t.status==='open').sort((a,b)=>a.date.localeCompare(b.date))}
function deadlinePanel(){if(!exam())return '';const pending=studyTasks(),completed=(exam().studyTasks||[]).filter(t=>t.status==='done').slice(-5).reverse();return `<section class="panel study-deadlines">${panelHead(studyKind()==='faculdade'?'Provas e entregas':'Seus próximos prazos','Prazos ajudam a orientar as prioridades de estudo.',btn('Adicionar prazo','deadline-new','','secondary small'))}${pending.slice(0,8).map(t=>`<div class="row"><div class="row-time">${dateLabel(t.date)}<small>${diffDays(today(),t.date)<0?'Atrasado':diffDays(today(),t.date)===0?'Hoje':diffDays(today(),t.date)+' dias'}</small></div><div class="row-main"><h3>${esc(t.title)}</h3><p>${esc(t.kind)}${t.subjectId?' · '+esc(subjectName(t.subjectId)):''}</p></div><div class="actions">${btn('Concluir','deadline-done',`data-id="${esc(t.id)}"`,'quiet small')}${btn('Editar','deadline-edit',`data-id="${esc(t.id)}"`,'quiet small')}</div></div>`).join('')||empty('Dê lugar aos seus prazos','Cadastre provas, trabalhos ou projetos. Concluir um prazo não registra tempo de estudo.')}${pending.length>8?`<details><summary>Mais ${pending.length-8} prazos</summary>${pending.slice(8).map(t=>`<div class="row"><div class="row-main"><h3>${esc(t.title)}</h3><p>${dateLabel(t.date)} · ${esc(t.kind)}</p></div>${btn('Editar','deadline-edit',`data-id="${esc(t.id)}"`,'quiet small')}</div>`).join('')}</details>`:''}${completed.length?`<details><summary>Concluídos recentemente</summary>${completed.map(t=>`<div class="row"><div class="row-main"><h3>${esc(t.title)}</h3><p>${dateLabel(t.date)}</p></div>${btn('Reabrir','deadline-reopen',`data-id="${esc(t.id)}"`,'quiet small')}</div>`).join('')}</details>`:''}</section>`}
function openDeadline(taskId){const e=exam();if(!e)return;const task=e.studyTasks?.find(t=>t.id===taskId);modal(task?'Editar prazo':'Um próximo passo com data','Associe uma matéria para ela receber atenção perto do prazo.',`<div class="form-grid"><label class="full">Título<input name="title" required maxlength="200" value="${esc(task?.title||'')}" placeholder="Ex.: Prova de Cálculo I"></label><label>Tipo<select name="kind">${['Prova','Trabalho','Projeto','Revisão','Outro'].map(k=>`<option ${task?.kind===k?'selected':''}>${k}</option>`).join('')}</select></label><label>Data<input type="date" name="date" required value="${task?.date||today()}"></label><label class="full">Matéria ou disciplina<select name="subjectId"><option value="">Sem matéria associada</option>${subjectOptions(task?.subjectId)}</select></label><p class="form-help full">O prazo não cria uma sessão nem muda seus horários sozinho. Gere o plano para obter uma nova sugestão e confira antes de aplicar.</p></div>`,'Salvar prazo',d=>{if(!d.title.trim()||!validDate(d.date))throw Error('Confira o título e a data.');if(d.subjectId&&!subject(d.subjectId))throw Error('Escolha uma matéria disponível.');if((e.studyTasks?.length||0)>=2000&&!task)throw Error('Você já tem 2.000 prazos neste espaço.');snapshot();e.studyTasks??=[];const values={title:d.title.trim(),kind:d.kind,date:d.date,subjectId:d.subjectId||null};if(task)Object.assign(task,values);else e.studyTasks.push({id:id(),status:'open',...values});closeModal();commit('Prazo salvo. Revise seu planejamento.',true)})}
function profileAIContext(e){const p=e.learningProfile,lines=[];if(p)lines.push('Objetivo: '+studyKinds[p.kind].label,'Momento: '+studyRoles[p.role],'Curso/área: '+(p.course||'Não informado'),'Etapa: '+(p.term||'Não informada'),'Base declarada: '+studyLevels[p.level],'Ajuda desejada: '+studyChallenges[p.challenge],'Preferência de prática: '+studyMethods[p.method],'Orientação: '+studyAdvice(p));if(studyTasks(e).length)lines.push('Prazos em aberto (até 8):',...studyTasks(e).slice(0,8).map(t=>'- '+t.date+' | '+t.kind+' | '+t.title+' | '+(e.subjects.find(s=>s.id===t.subjectId)?.name||'Sem disciplina associada')));return lines.join('\n')}
Object.assign(actions,{'exam-new':()=>profileBegin(false),'profile-new':()=>profileBegin(false),'profile-edit':()=>profileBegin(true),'profile-cancel':()=>{profileDraft=null;profileEditingId=null;profileStep=0;go('hoje')},'profile-kind':b=>{profileDraft.kind=b.dataset.profileKind;profileStep=1;render();$('#profile-heading')?.focus({preventScroll:true})},'profile-back':()=>{if($('#profile-wizard'))profileRead($('#profile-wizard'));profileStep=Math.max(0,profileStep-1);render();$('#profile-heading')?.focus({preventScroll:true})},'profile-tour':()=>startTour('perfil'),'deadline-new':()=>openDeadline(),'deadline-edit':b=>openDeadline(b.dataset.id),'deadline-done':b=>{const t=exam()?.studyTasks?.find(t=>t.id===b.dataset.id);if(t){snapshot();t.status='done';commit('Prazo concluído. O histórico de estudos permanece separado.',true)}},'deadline-reopen':b=>{const t=exam()?.studyTasks?.find(t=>t.id===b.dataset.id);if(t){snapshot();t.status='open';commit('Prazo reaberto.',true)}}});
document.addEventListener('submit',event=>{if(event.target.id!=='profile-wizard')return;event.preventDefault();try{profileRead(event.target);profileValidateStep();if(profileStep===4)profileFinish();else{profileStep++;render();$('#profile-heading')?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'})}}catch(error){$('#profile-error').textContent=error.message}});
function viewDeadlines(){return heading('Cada prazo, um próximo passo.','Organize provas, trabalhos e projetos. Associe disciplinas para orientar suas prioridades.')+deadlinePanel()}
function viewPersonalToday(){return viewToday()+deadlinePanel()}
function viewPersonalPlan(){return viewPlan()+deadlinePanel()}
function studyDeadlinePriority(subjectId){const pending=studyTasks().filter(t=>t.subjectId===subjectId);if(!pending.length)return 0;return Math.max(...pending.map(t=>Math.max(0,14-Math.max(0,diffDays(today(),t.date)))*.75))}
function studyTourCapture(){return {draft:profileDraft?clone(profileDraft):null,step:profileStep,editingId:profileEditingId,alarm:clone(focusAlarmSettings),alert:timerAlert,ai:{aiMode,aiContent,aiSubmittedContent,aiResult:aiResult?clone(aiResult):null,aiError,aiExamId,aiQuizIndex,aiUseContext,aiQuestionCount,aiDifficulty,aiGeneratedDifficulty}}}
function studyTourSetup(){if(timerPip&&!timerPip.closed)timerPip.close();aiCleanupWidget();profileDraft=null;profileEditingId=null;profileStep=0;aiMode='explain';aiContent='Na revisão ativa, tento lembrar antes de consultar o material. Depois confiro, explico com minhas palavras e retomo o assunto em outro dia.';aiSubmittedContent='';aiResult=null;aiError='';aiUseContext=false;aiQuestionCount=3;aiDifficulty='medium';timerAlert='';focusAlarmSettings={sound:false,atMinutes:0};exam().studyTasks=[{id:id(),title:'Prova de prática',date:addDays(today(),3),kind:'Prova',subjectId:exam().subjects[0].id,status:'open'}]}
function studyTourRestore(state){if(!state)return;profileDraft=state.draft;profileStep=state.step;profileEditingId=state.editingId;focusAlarmSettings=state.alarm;timerAlert=state.alert;aiCleanupWidget();({aiMode,aiContent,aiSubmittedContent,aiResult,aiError,aiExamId,aiQuizIndex,aiUseContext,aiQuestionCount,aiDifficulty,aiGeneratedDifficulty}=state.ai);timerDockKey='';timerPipKey=''}
function profileTourStep(n){profileBegin(true,false);Object.assign(profileDraft,{kind:'faculdade',role:'estudante',course:'Administração',goal:'Meu semestre de prática',term:'2º semestre',applyRoutine:false});profileStep=n;render()}
function studyAIPractice(mode='quiz',revealed=false){if(!tour)return;aiMode=mode;aiCleanupWidget();aiSubmittedContent=aiContent;aiQuizIndex=0;aiExamId=exam().id;aiGeneratedDifficulty=aiDifficulty;aiError='';aiResult=mode==='explain'?{explanation:'DEMONSTRAÇÃO DO TUTORIAL. Recuperação ativa significa tentar lembrar antes de consultar. Por exemplo, feche o material e explique o conceito em voz alta. Depois confira o que faltou. Distribuir essas revisões ao longo dos dias ajuda a retomar o conteúdo.'}:mode==='cards'?{cards:Array.from({length:4},(_,i)=>({front:['O que é recuperação ativa?','Quando conferir o material?','Como distribuir revisões?','O que fazer ao esquecer?'][i],back:['Tentar lembrar antes de consultar.','Depois de tentar responder com suas palavras.','Retomar o assunto em dias diferentes.','Conferir o raciocínio, identificar o que faltou e praticar novamente.'][i]}))}:{questions:Array.from({length:aiQuestionCount},(_,i)=>({prompt:'Prática '+(i+1)+': Qual estratégia aplica a recuperação ativa?',options:['Reler o texto continuamente sem tentar lembrar.','Tentar explicar sem consultar e depois conferir o material.','Copiar todas as páginas antes de começar.','Evitar conferir as dúvidas para manter o ritmo.'],answer:1,explanation:'Tentar lembrar antes de consultar exige recuperar o conteúdo. Conferir depois ajuda a encontrar lacunas e corrigir o raciocínio. A alternativa B combina essas duas etapas. Este exemplo é uma demonstração local do tutorial.',optionExplanations:['Reler não garante que você consiga recuperar o conteúdo.','Combina recuperação e conferência do raciocínio.','Copiar sozinho não exige recuperar a ideia.','Conferir dúvidas é parte da correção.'],takeaway:'Primeiro tente lembrar. Depois confira e explique o que faltou.',...(revealed&&i===0?{choice:1,revealed:true}:{})}))};render()}
tourAreas.foco.steps.push(
 tStep('#timer-reminder','Um aviso no momento certo.','Escolha após quantos minutos de estudo quer receber um lembrete. Use 0 para desligar. Na contagem regressiva, escolha um tempo menor que o bloco.',{prepare:()=>{if(!db.timer)startFocus(exam().subjects[0].id);render()}}),
 tStep('#timer-sound','Um som para lembrar de pausar.','Ative o áudio e use Testar som fora do tutorial. O alarme toca no lembrete e ao chegar a zero. Durante esta prática, o som fica desativado.'),
 tStep('[data-action="timer-dock-open"]','Leve o foco para outras telas.','Abrir minipainel mostra um cronômetro arrastável. Ele acompanha as telas do Norte e permite pausar ou registrar.',{click:'dock'}),
 tStep('#timer-dock [data-timer-drag]','Arraste o seu minipainel.','Segure o cabeçalho e arraste para um lugar confortável. Ao soltar, o painel se acomoda dentro da tela. Você também pode pausar e registrar por ele.',{prepare:()=>{if(!db.timer)startFocus(exam().subjects[0].id);db.timer.dockVisible=true;db.timer.dockOnFocus=true;render()}}),
 tStep('[data-action="timer-pip"]','Uma janela sobre outros aplicativos.','Flutuar sobre outras janelas funciona em navegadores compatíveis. Mantenha a aba original aberta. Este recurso externo fica desativado no tutorial.',{observeOnly:true})
);
tourAreas.perfil={label:'Meu perfil',caption:'Um espaço para o seu objetivo',steps:[
 tStep('[data-profile-kind="faculdade"]','O Norte se adapta ao seu momento.','Escolha faculdade, concurso, escola, certificação ou aprendizado pessoal. O perfil vale para o espaço ativo, sem misturar preparações.',{prepare:()=>profileTourStep(0),click:'profile'}),
 tStep('#profile-course','A NORBIT começa conhecendo você.','Informe seu curso ou área. Seu momento, objetivo e etapa orientam o painel. Esta conversa guiada funciona no aparelho, sem pedidos externos.',{prepare:()=>profileTourStep(1)}),
 tStep('#profile-challenge','Uma ajuda mais coerente.','Escolha onde precisa de reforço: tempo, constância, compreensão, memória ou prática. A preferência indica por onde começar, sem limitar como você aprende.',{prepare:()=>profileTourStep(2)}),
 tStep('#profile-routine','Uma rotina que cabe na sua vida.','Escolha dias, minutos e horários. Ao editar, marque Aplicar esta nova rotina apenas se quiser mudar as metas; planos existentes são preservados.',{prepare:()=>profileTourStep(3)}),
 tStep('.profile-review','Confira antes de adaptar.','O resumo mostra seu perfil e sua rotina. Salvar atualiza este espaço. Novos estudos podem receber uma primeira semana; registros existentes são preservados.',{prepare:()=>profileTourStep(4)})
]};
tourAreas.prazos={label:'Prazos',caption:'Provas, trabalhos e projetos',steps:[
 tStep('[data-action="deadline-new"]','Cada entrega tem um lugar.','Clique em Adicionar prazo. Uma prova, um trabalho ou projeto pode ser associado a uma disciplina.',{click:'open'}),
 tStep('#modal [name="title"]','Dê um nome claro ao próximo passo.','Use um título concreto, como Prova de Cálculo I. Informe uma data e a disciplina relacionada.',{prepare:()=>openDeadline(),modal:true}),
 tStep('#modal [name="subjectId"]','Um prazo orienta a prioridade.','Nos 14 dias anteriores ao prazo, a disciplina recebe mais atenção nas sugestões. Gere e confira um plano novo; seus horários não mudam sozinhos.',{prepare:()=>openDeadline(),modal:true}),
 tourSaveStep('Guarde seu prazo de prática.','Salve o exemplo. Ele aparecerá no painel e no Planejamento; os dados desta prática serão descartados ao sair.',()=>openDeadline(),()=>tourFillFields({title:'Entrega de prática',date:addDays(today(),5)})),
 tStep('[data-action="deadline-done"]','Concluir uma entrega não registra estudo.','Marque o prazo como concluído quando terminar. Para registrar tempo ou questões, use + Registrar. Você pode reabrir prazos e desfazer a ação.',{click:'deadline'})
]};
tourAreas.ia={label:'NORBIT AI',caption:'Explicar, memorizar e praticar',steps:[
 tStep('.norbit-suggestions','Três maneiras de aprender.','Peça uma explicação, crie cartões ou pratique questões. Neste tour, as respostas são exemplos locais e não consomem sua cota.',{prepare:()=>{aiResult=null;aiMode='explain';render()}}),
 tStep('[data-action="ai-mode"][data-mode="quiz"]','Prepare um treino seu.','Escolha Praticar questões. Você decide a quantidade e o nível antes de gerar.',{click:'mode'}),
 tStep('[name="questionCount"]','De uma a dez questões.','Escolha o tamanho do treino. Responder e revisar os erros costuma valer mais que gerar muitos itens.',{prepare:()=>{aiMode='quiz';aiResult=null;render()}}),
 tStep('[name="difficulty"]','Escolha a dificuldade.','Fácil trabalha reconhecimento. Médio aplica conceitos. Difícil conecta ideias. Ajuste conforme seu objetivo.'),
 tStep('#ai-content','Traga o conteúdo real.','Envie uma dúvida, trecho ou questão de 20 a 8.000 caracteres. A IA deve trabalhar sobre o material que você escolheu.'),
 tStep('[name="studyContext"]','Seu perfil dá contexto.','Ative o contexto para usar perfil, metas, disciplinas, prazos e atividades. Você pode conferir o resumo antes de autorizar. Anotações pessoais e backups ficam fora.',{prepare:()=>{aiUseContext=true;render()}}),
 tStep('.ai-context-preview','Você escolhe o que é enviado.','O resumo pertence ao espaço ativo. Trocar o espaço troca o contexto. Desativar esta opção envia apenas o texto escolhido.',{prepare:()=>{aiUseContext=true;render()}}),
 tStep('[name="consent"]','Autorize cada envio real.','Fora do tutorial, confirme o envio e faça a verificação humana. O perfil fica local até você ativar o contexto e autorizar. Aqui não há envio externo.'),
 tStep('.norbit-send','Experimente sem gastar a cota.','Neste tour, enviar mostra uma resposta de demonstração. No uso real, há uma cota compartilhada para o site e uma por rede de acesso.',{click:'practice'}),
 tStep('[name="ai-q-0"]','Responda antes de ver o resultado.','Escolha uma alternativa. Você pode navegar entre questões antes de conferir.',{prepare:()=>studyAIPractice('quiz')}),
 tStep('[data-action="ai-answer"]','Confira sua resposta.','Depois de selecionar uma alternativa, clique em Responder questão. A NORBIT mostra acerto ou erro e o mascote responde ao resultado.'),
 tStep('.ai-rationale','Entenda o raciocínio.','Leia a explicação, confira cada alternativa e leve a dica para a próxima questão. O treino não altera as estatísticas do histórico.',{prepare:()=>studyAIPractice('quiz',true)}),
 tStep('.ai-alternative-reasons','Aprenda também com as alternativas.','Abra esta seção para entender por que cada opção funciona ou não. Confira respostas da IA no seu material.'),
 tStep('#ai-save-form','Cartões que você pode revisar.','Edite perguntas e respostas, escolha os cartões e a disciplina. Só serão guardados quando você clicar em Adicionar selecionados.',{prepare:()=>studyAIPractice('cards')}),
 tStep('.norbit-details','Seus dados e sua cota.','Consulte aqui os limites e a privacidade. Cancelar interrompe o pedido; um pedido já enviado ao serviço pode ter consumido cota.')
]};
