// Mascot motion, study deadlines and local live tutorial demonstrations.
const NORBIT_MASCOT='__NORBIT_MASCOT__';
const studyKinds={concurso:{syllabus:"Meu edital",date:"Data da prova"}};
function studyKind(){return "concurso"}
function studyLabel(key){return routes.find(r=>r[0]===key)?.[1]||key}
function norbitMascot(state='welcome',size='small'){const sprite='<img src="'+NORBIT_MASCOT+'" alt="" width="512" height="512" draggable="false">';return '<span class="norbit-mascot mascot-'+size+'" data-state="'+state+'" aria-hidden="true"><span class="mascot-figure"><span class="mascot-body">'+sprite+'</span><span class="mascot-hand mascot-hand-left">'+sprite+'</span><span class="mascot-hand mascot-hand-right">'+sprite+'</span><i class="mascot-lid mascot-lid-left"></i><i class="mascot-lid mascot-lid-right"></i></span><i class="mascot-spark"></i></span>'}

function studyTasks(e=exam()){return (e?.studyTasks||[]).filter(t=>t.status==='open').sort((a,b)=>a.date.localeCompare(b.date))}
function deadlinePanel(){if(!exam())return '';const pending=studyTasks(),completed=(exam().studyTasks||[]).filter(t=>t.status==='done').slice(-5).reverse();return `<section class="panel study-deadlines">${panelHead(studyKind()==='faculdade'?'Provas e entregas':'Seus próximos prazos','Prazos ajudam a orientar as prioridades de estudo.',btn('Adicionar prazo','deadline-new','','secondary small'))}${pending.slice(0,8).map(t=>`<div class="row"><div class="row-time">${dateLabel(t.date)}<small>${diffDays(today(),t.date)<0?'Atrasado':diffDays(today(),t.date)===0?'Hoje':diffDays(today(),t.date)+' dias'}</small></div><div class="row-main"><h3>${esc(t.title)}</h3><p>${esc(t.kind)}${t.subjectId?' · '+esc(subjectName(t.subjectId)):''}</p></div><div class="actions">${btn('Concluir','deadline-done',`data-id="${esc(t.id)}"`,'quiet small')}${btn('Editar','deadline-edit',`data-id="${esc(t.id)}"`,'quiet small')}</div></div>`).join('')||empty('Dê lugar aos seus prazos','Cadastre provas, trabalhos ou projetos. Concluir um prazo não registra tempo de estudo.')}${pending.length>8?`<details><summary>Mais ${pending.length-8} prazos</summary>${pending.slice(8).map(t=>`<div class="row"><div class="row-main"><h3>${esc(t.title)}</h3><p>${dateLabel(t.date)} · ${esc(t.kind)}</p></div>${btn('Editar','deadline-edit',`data-id="${esc(t.id)}"`,'quiet small')}</div>`).join('')}</details>`:''}${completed.length?`<details><summary>Concluídos recentemente</summary>${completed.map(t=>`<div class="row"><div class="row-main"><h3>${esc(t.title)}</h3><p>${dateLabel(t.date)}</p></div>${btn('Reabrir','deadline-reopen',`data-id="${esc(t.id)}"`,'quiet small')}</div>`).join('')}</details>`:''}</section>`}
function openDeadline(taskId){const e=exam();if(!e)return;const task=e.studyTasks?.find(t=>t.id===taskId);modal(task?'Editar prazo':'Um próximo passo com data','Associe uma matéria para ela receber atenção perto do prazo.',`<div class="form-grid"><label class="full">Título<input name="title" required maxlength="200" value="${esc(task?.title||'')}" placeholder="Ex.: Prova de Cálculo I"></label><label>Tipo<select name="kind">${['Prova','Trabalho','Projeto','Revisão','Outro'].map(k=>`<option ${task?.kind===k?'selected':''}>${k}</option>`).join('')}</select></label><label>Data<input type="date" name="date" required value="${task?.date||today()}"></label><label class="full">Matéria ou disciplina<select name="subjectId"><option value="">Sem matéria associada</option>${subjectOptions(task?.subjectId)}</select></label><p class="form-help full">O prazo não cria uma sessão nem muda seus horários sozinho. Gere o plano para obter uma nova sugestão e confira antes de aplicar.</p></div>`,'Salvar prazo',d=>{if(!d.title.trim()||!validDate(d.date))throw Error('Confira o título e a data.');if(d.subjectId&&!subject(d.subjectId))throw Error('Escolha uma matéria disponível.');if((e.studyTasks?.length||0)>=2000&&!task)throw Error('Você já tem 2.000 prazos neste espaço.');snapshot();e.studyTasks??=[];const values={title:d.title.trim(),kind:d.kind,date:d.date,subjectId:d.subjectId||null};if(task)Object.assign(task,values);else e.studyTasks.push({id:id(),status:'open',...values});closeModal();commit('Prazo salvo. Revise seu planejamento.',true)})}
function deadlineAIContext(e){return studyTasks(e).length?['Prazos em aberto (até 8):',...studyTasks(e).slice(0,8).map(t=>'- '+t.date+' | '+t.kind+' | '+t.title+' | '+(e.subjects.find(s=>s.id===t.subjectId)?.name||'Sem disciplina associada'))].join('\n'):''}
Object.assign(actions,{'deadline-new':()=>openDeadline(),'deadline-edit':b=>openDeadline(b.dataset.id),'deadline-done':b=>{const t=exam()?.studyTasks?.find(t=>t.id===b.dataset.id);if(t){snapshot();t.status='done';commit('Prazo concluído. O histórico de estudos permanece separado.',true)}},'deadline-reopen':b=>{const t=exam()?.studyTasks?.find(t=>t.id===b.dataset.id);if(t){snapshot();t.status='open';commit('Prazo reaberto.',true)}}});
function viewDeadlines(){return heading('Cada prazo, um próximo passo.','Organize provas, trabalhos e projetos. Associe disciplinas para orientar suas prioridades.')+deadlinePanel()}
function viewPersonalToday(){return viewToday()+deadlinePanel()}
function viewPersonalPlan(){return viewPlan()+deadlinePanel()}
function studyDeadlinePriority(subjectId){const pending=studyTasks().filter(t=>t.subjectId===subjectId);if(!pending.length)return 0;return Math.max(...pending.map(t=>Math.max(0,14-Math.max(0,diffDays(today(),t.date)))*.75))}
function studyTourCapture(){return {alarm:clone(focusAlarmSettings),alert:timerAlert,ai:{aiMode,aiContent,aiSubmittedContent,aiResult:aiResult?clone(aiResult):null,aiError,aiExamId,aiQuizIndex,aiUseContext,aiQuestionCount,aiDifficulty,aiGeneratedDifficulty}}}
function studyTourSetup(){if(timerPip&&!timerPip.closed)timerPip.close();aiCleanupWidget();aiMode='explain';aiContent='Na revisão ativa, tento lembrar antes de consultar o material. Depois confiro, explico com minhas palavras e retomo o assunto em outro dia.';aiSubmittedContent='';aiResult=null;aiError='';aiUseContext=false;aiQuestionCount=3;aiDifficulty='medium';timerAlert='';focusAlarmSettings={sound:false,atMinutes:0};exam().studyTasks=[{id:id(),title:'Prova de prática',date:addDays(today(),3),kind:'Prova',subjectId:exam().subjects[0].id,status:'open'}]}
function studyTourRestore(state){if(!state)return;focusAlarmSettings=state.alarm;timerAlert=state.alert;aiCleanupWidget();({aiMode,aiContent,aiSubmittedContent,aiResult,aiError,aiExamId,aiQuizIndex,aiUseContext,aiQuestionCount,aiDifficulty,aiGeneratedDifficulty}=state.ai);timerDockKey='';timerPipKey=''}
function studyAIPractice(mode='quiz',revealed=false){if(!tour)return;aiMode=mode;aiCleanupWidget();aiSubmittedContent=aiContent;aiQuizIndex=0;aiExamId=exam().id;aiGeneratedDifficulty=aiDifficulty;aiError='';aiResult=mode==='explain'?{explanation:'DEMONSTRAÇÃO DO TUTORIAL. Recuperação ativa significa tentar lembrar antes de consultar. Por exemplo, feche o material e explique o conceito em voz alta. Depois confira o que faltou. Distribuir essas revisões ao longo dos dias ajuda a retomar o conteúdo.'}:mode==='cards'?{cards:Array.from({length:4},(_,i)=>({front:['O que é recuperação ativa?','Quando conferir o material?','Como distribuir revisões?','O que fazer ao esquecer?'][i],back:['Tentar lembrar antes de consultar.','Depois de tentar responder com suas palavras.','Retomar o assunto em dias diferentes.','Conferir o raciocínio, identificar o que faltou e praticar novamente.'][i]}))}:{questions:Array.from({length:aiQuestionCount},(_,i)=>({prompt:'Prática '+(i+1)+': Qual estratégia aplica a recuperação ativa?',options:['Reler o texto continuamente sem tentar lembrar.','Tentar explicar sem consultar e depois conferir o material.','Copiar todas as páginas antes de começar.','Evitar conferir as dúvidas para manter o ritmo.'],answer:1,explanation:'Tentar lembrar antes de consultar exige recuperar o conteúdo. Conferir depois ajuda a encontrar lacunas e corrigir o raciocínio. A alternativa B combina essas duas etapas. Este exemplo é uma demonstração local do tutorial.',optionExplanations:['Reler não garante que você consiga recuperar o conteúdo.','Combina recuperação e conferência do raciocínio.','Copiar sozinho não exige recuperar a ideia.','Conferir dúvidas é parte da correção.'],takeaway:'Primeiro tente lembrar. Depois confira e explique o que faltou.',...(revealed&&i===0?{choice:1,revealed:true}:{})}))};render()}
tourAreas.foco.steps.push(
 tStep('#timer-reminder','Um aviso no momento certo.','Escolha após quantos minutos de estudo quer receber um lembrete. Use 0 para desligar. Na contagem regressiva, escolha um tempo menor que o bloco.',{prepare:()=>{if(!db.timer)startFocus(exam().subjects[0].id);render()}}),
 tStep('#timer-sound','Um som para lembrar de pausar.','Ative o áudio e use Testar som fora do tutorial. O alarme toca no lembrete e ao chegar a zero. Durante esta prática, o som fica desativado.'),
 tStep('[data-action="timer-dock-open"]','Leve o foco para outras telas.','Abrir minipainel mostra um cronômetro arrastável. Ele acompanha as telas do Norte e permite pausar ou registrar.',{click:'dock'}),
 tStep('#timer-dock [data-timer-drag]','Arraste o seu minipainel.','Segure o cabeçalho e arraste para um lugar confortável. Ao soltar, o painel se acomoda dentro da tela. Você também pode pausar e registrar por ele.',{prepare:()=>{if(!db.timer)startFocus(exam().subjects[0].id);db.timer.dockVisible=true;db.timer.dockOnFocus=true;render()}}),
 tStep('[data-action="timer-pip"]','Uma janela sobre outros aplicativos.','Flutuar sobre outras janelas funciona em navegadores compatíveis. Mantenha a aba original aberta. Este recurso externo fica desativado no tutorial.',{observeOnly:true})
);
tourAreas.prazos={label:'Prazos',caption:'Provas, trabalhos e projetos',steps:[
 tStep('[data-action="deadline-new"]','Cada entrega tem um lugar.','Clique em Adicionar prazo. Uma prova, um trabalho ou projeto pode ser associado a uma disciplina.',{click:'open'}),
 tStep('#modal [name="title"]','Dê um nome claro ao próximo passo.','Use um título concreto, como Prova de Cálculo I. Informe uma data e a disciplina relacionada.',{prepare:()=>openDeadline(),modal:true}),
 tStep('#modal [name="subjectId"]','Um prazo orienta a prioridade.','Nos 14 dias anteriores ao prazo, a disciplina recebe mais atenção nas sugestões. Gere e confira um plano novo; seus horários não mudam sozinhos.',{prepare:()=>openDeadline(),modal:true}),
 tourSaveStep('Guarde seu prazo de prática.','Salve o exemplo. Ele aparecerá no painel e no Planejamento; os dados desta prática serão descartados ao sair.',()=>openDeadline(),()=>tourFillFields({title:'Entrega de prática',date:addDays(today(),5)})),
 tStep('[data-action="deadline-done"]','Concluir uma entrega não registra estudo.','Marque o prazo como concluído quando terminar. Para registrar tempo ou questões, use + Registrar. Você pode reabrir prazos e desfazer a ação.',{click:'deadline'})
]};
tourAreas.ia={label:'NORBIT AI',caption:'Explicar, memorizar e praticar',steps:[
 tStep('.norbit-suggestions','Três maneiras de aprender.','Peça uma explicação, crie cartões ou pratique questões. Neste tour, as respostas são exemplos locais e não consomem sua cota.',{prepare:()=>{aiResult=null;aiMode='explain';render()}}),
 tStep('[data-action="ai-mode"][data-mode="quiz"]','Prepare um treino seu.','Escolha Praticar questões. Você decide a quantidade e o nível antes de gerar.',{click:'mode'}),
 tStep('[name="questionCount"]','De uma a dez questões.','Escolha o tamanho do treino. Responder e revisar os erros costuma valer mais que gerar muitos itens.',{prepare:()=>{aiMode='quiz';aiResult=null;render()}}),
 tStep('[name="difficulty"]','Escolha a dificuldade.','Fácil trabalha reconhecimento. Médio aplica conceitos. Difícil conecta ideias. Ajuste conforme seu objetivo.'),
 tStep('#ai-content','Traga o conteúdo real.','Envie uma dúvida, trecho ou questão de 20 a 8.000 caracteres. A IA deve trabalhar sobre o material que você escolheu.'),
 tStep('[name="studyContext"]','Seu planejamento dá contexto.','Ative o contexto para usar metas, disciplinas, prazos e atividades. Você pode conferir o resumo antes de autorizar. Anotações pessoais e backups ficam fora.',{prepare:()=>{aiUseContext=true;render()}}),
 tStep('.ai-context-preview','Você escolhe o que é enviado.','O resumo pertence ao espaço ativo. Trocar o espaço troca o contexto. Desativar esta opção envia apenas o texto escolhido.',{prepare:()=>{aiUseContext=true;render()}}),
 tStep('[name="consent"]','Autorize cada envio real.','Fora do tutorial, confirme o envio e faça a verificação humana. Seus registros ficam locais até você ativar o contexto e autorizar. Aqui não há envio externo.'),
 tStep('.norbit-send','Experimente sem gastar a cota.','Neste tour, enviar mostra uma resposta de demonstração. No uso real, há uma cota compartilhada para o site e uma por rede de acesso.',{click:'practice'}),
 tStep('[name="ai-q-0"]','Responda antes de ver o resultado.','Escolha uma alternativa. Você pode navegar entre questões antes de conferir.',{prepare:()=>studyAIPractice('quiz')}),
 tStep('[data-action="ai-answer"]','Confira sua resposta.','Depois de selecionar uma alternativa, clique em Responder questão. A NORBIT mostra acerto ou erro e o mascote responde ao resultado.'),
 tStep('.ai-rationale','Entenda o raciocínio.','Leia a explicação, confira cada alternativa e leve a dica para a próxima questão. O treino não altera as estatísticas do histórico.',{prepare:()=>studyAIPractice('quiz',true)}),
 tStep('.ai-alternative-reasons','Aprenda também com as alternativas.','Abra esta seção para entender por que cada opção funciona ou não. Confira respostas da IA no seu material.'),
 tStep('#ai-save-form','Cartões que você pode revisar.','Edite perguntas e respostas, escolha os cartões e a disciplina. Só serão guardados quando você clicar em Adicionar selecionados.',{prepare:()=>studyAIPractice('cards')}),
 tStep('.norbit-details','Seus dados e sua cota.','Consulte aqui os limites e a privacidade. Cancelar interrompe o pedido; um pedido já enviado ao serviço pode ter consumido cota.')
]};
