/* Connected study tools. New records remain inside each preparation's backup. */
let studyTopicId=null,studySubjectId=null,concentration=false,recoveryPreview=[];
const dashboardPanels=[['queue','Minha fila'],['plan','Plano de hoje'],['goals','Metas'],['reviews','Revisões'],['coverage','Cobertura'],['deadlines','Prazos']];
function studio(e=exam()){return e?.studio||{bank:[],attempts:[],cache:[],reviewLog:[],notes:{},layout:{order:dashboardPanels.map(x=>x[0]),hidden:[]},lastBackup:null}}
function writeStudio(e=exam()){if(!e)return null;return e.studio??=studio(e)}
function studioRoom(){if(JSON.stringify(studio()).length>1500000)throw Error('Este espaço de ferramentas está cheio. Exporte um backup e remova treinos antigos ou respostas salvas.')}
const baseBackupValidator=validateBackup;
validateBackup=function(data){
 baseBackupValidator(data);
 const fail=()=>{throw Error('Os dados das ferramentas de estudo estão inválidos. O backup não foi aplicado.')};
 const text=(x,n)=>typeof x==='string'&&x.length<=n;
 for(const e of data.exams){if(!e.studio)continue;const d=e.studio;
  if(!d||JSON.stringify(d).length>1500000||!Array.isArray(d.bank)||d.bank.length>500||!Array.isArray(d.attempts)||d.attempts.length>100||!Array.isArray(d.cache)||d.cache.length>20||!Array.isArray(d.reviewLog)||d.reviewLog.length>1000||!d.notes||Array.isArray(d.notes)||typeof d.notes!=='object'||Object.entries(d.notes).length>1000)fail();
  const ids=new Set();for(const q of d.bank){if(!text(q.id,150)||!q.id||ids.has(q.id)||!validBankQuestion(q)||!e.subjects.some(s=>s.id===q.subjectId&&(!q.topicId||s.topics.some(t=>t.id===q.topicId))))fail();ids.add(q.id)}
  for(const a of d.attempts){if(!text(a.id,150)||!validDate(a.date)||!text(a.title,200)||!Number.isInteger(a.minutes)||!num(a.minutes,0,1440)||!Array.isArray(a.questions)||a.questions.length<1||a.questions.length>50||!Array.isArray(a.choices)||a.choices.length!==a.questions.length||a.choices.some(c=>c!==null&&(!Number.isInteger(c)||!num(c,0,3)))||a.questions.some(q=>!validBankQuestion(q))||a.sessionIds!==undefined&&(!Array.isArray(a.sessionIds)||a.sessionIds.some(v=>!text(v,150))))fail()}
  for(const row of d.cache)if(!text(row.key,64)||!text(row.label,120)||!text(row.date,50)||!Number.isFinite(Date.parse(row.date))||!['explain','cards','quiz'].includes(row.mode)||!aiValidResult(row.mode,row.result,row.result?.questions?.length||3))fail();
  for(const row of d.reviewLog)if(!text(row.topicId,150)||!validDate(row.date)||!['again','hard','good','easy'].includes(row.rating)||!num(row.interval,1,180))fail();
  for(const [key,value] of Object.entries(d.notes))if(!text(key,150)||!text(value,12000))fail();
  if(d.lastBackup!==null&&!validDate(d.lastBackup))fail();
  if(!d.layout||!Array.isArray(d.layout.order)||!Array.isArray(d.layout.hidden)||new Set(d.layout.order).size!==dashboardPanels.length||d.layout.order.length!==dashboardPanels.length||d.layout.order.some(k=>!dashboardPanels.some(x=>x[0]===k))||d.layout.hidden.some(k=>!dashboardPanels.some(x=>x[0]===k)))fail();
 }
 return true;
};
function validBankQuestion(q){return q&&typeof q.prompt==='string'&&q.prompt.trim()&&q.prompt.length<=12000&&Array.isArray(q.options)&&q.options.length===4&&q.options.every(v=>typeof v==='string'&&v.trim()&&v.length<=3000)&&new Set(q.options.map(v=>v.trim().toLocaleLowerCase())).size===4&&Number.isInteger(q.answer)&&num(q.answer,0,3)&&typeof q.explanation==='string'&&q.explanation.length<=12000&&['easy','medium','hard'].includes(q.difficulty)&&typeof q.source==='string'&&q.source.length<=200}
function backupNotice(){if(!exam()||tour)return '';const date=studio().lastBackup;if(date&&diffDays(date,today())<7)return '';return `<aside class="backup-notice"><div><strong>Proteja seu progresso.</strong><p>${date?'Último backup registrado há '+diffDays(date,today())+' dias.':'Ainda não há um backup registrado desta preparação.'}</p></div>${btn('Exportar backup','export','','secondary small')}</aside>`}
const exportBeforeStudio=exportBackup;exportBackup=function(){if(!tour)db.exams.forEach(e=>writeStudio(e).lastBackup=today());exportBeforeStudio();persist()};actions.export=()=>exportBackup();
function learningQueue(){
 if(!exam())return [];const result=[],seen=new Set();
 const add=(sid,tid,kind,itemId,title,why,minutes)=>{const s=subject(sid),t=topic(sid,tid);if(!s||s.archived||!t||seen.has(tid))return;seen.add(tid);result.push({sid,tid,kind,itemId,title,why,minutes})};
 dueCards().forEach(c=>add(c.subjectId,c.topicId,'card',c.id,c.front,'Cartão disponível · recupere a resposta antes de revelar',5));
 dueTopics().forEach(x=>add(x.s.id,x.t.id,'review',x.t.id,x.t.name,'Revisão disponível · tente explicar sem consultar',10));
 exam().mistakes.filter(m=>!m.resolved).forEach(m=>add(m.subjectId,m.topicId,'mistake',m.id,m.title,'Dificuldade em aberto · retome a regra correta',10));
 exam().plans.filter(p=>p.date===today()&&p.status==='planned').sort((a,b)=>a.start.localeCompare(b.start)).forEach(p=>add(p.subjectId,p.topicId,'topic',p.id,topicName(p.subjectId,p.topicId),'Planejado para hoje',Math.min(25,timeMin(p.end)-timeMin(p.start))));
 recommendations().forEach(x=>add(x.s.id,x.t.id,'topic',x.t.id,x.t.name,reason(x.s,x.t),25));
 let remaining=quickMinutes;return result.map(x=>{if(remaining<=0)return null;const allocated=Math.min(remaining,x.minutes);remaining-=allocated;return {...x,minutes:allocated}}).filter(Boolean).slice(0,5);
}
function queuePanel(){return `<section class="panel quick-start" id="quick-start">${panelHead('Sua fila, no tempo que você tem.','Uma sequência de memória, revisão e estudo, com prioridades explicadas.')}<div class="quick-start-controls"><label for="quick-minutes">Tempo disponível</label><select id="quick-minutes">${[10,15,25,45,60].map(n=>`<option value="${n}" ${quickMinutes===n?'selected':''}>${n} minutos</option>`).join('')}</select>${btn('Atualizar fila','queue-refresh','','quiet small')}</div><div class="quick-targets">${learningQueue().map((x,i)=>`<div class="row"><span class="queue-number">${i+1}</span><div class="row-main"><h3>${esc(x.title)}</h3><p>${esc(subjectName(x.sid))} · ${esc(x.why)}</p><small>${x.minutes} minutos sugeridos</small></div>${btn('Começar','queue-start',`data-index="${i}"`,'secondary small')}${btn('Detalhes','topic-hub',`data-sid="${x.sid}" data-tid="${x.tid}"`,'quiet small')}</div>`).join('')||empty('Dê direção ao seu estudo','Adicione assuntos; cartões sem assunto continuam disponíveis na área Cartões.',btn('Organizar assuntos','navigate','data-route="edital"'))}</div><p class="form-help">Sugestões locais, sem chamadas à IA. Estudar e registrar continuam sendo decisões suas.</p></section>`}
const todayBeforeStudio=viewPersonalToday;
viewPersonalToday=function(){
 if(tour)return todayBeforeStudio();
 const fragment=document.createElement('template');fragment.innerHTML=viewToday();
 const grid=fragment.content.querySelector('.grid.two'),panels=[...grid.querySelectorAll('.panel')];
 const content={queue:queuePanel(),plan:panels[0]?.outerHTML||'',goals:panels[2]?.outerHTML||'',reviews:panels[3]?.outerHTML||'',coverage:panels[4]?.outerHTML||'',deadlines:deadlinePanel()};
 const layout=studio().layout;
 return fragment.content.querySelector('.page-heading').outerHTML+backupNotice()+`<div class="dashboard-tools">${btn('Personalizar painel','dashboard-edit','','quiet small')}${btn('Ver todos os assuntos','subjects-hub','','secondary small')}</div>`+fragment.content.querySelector('.metrics').outerHTML+`<div class="dashboard-grid">${layout.order.filter(k=>!layout.hidden.includes(k)).map(k=>`<div class="dashboard-block" data-dashboard="${k}">${content[k]}</div>`).join('')}</div>`;
};
function customizeDashboard(){const layout=studio().layout;modal('Seu painel, seu ritmo','Escolha os blocos e reorganize com os botões. A fila continua acessível em Revisões.',`<div class="dashboard-editor">${layout.order.map(k=>`<div class="row"><label class="checkbox-label"><input type="checkbox" data-dashboard-visible="${k}" ${layout.hidden.includes(k)?'':'checked'}>${dashboardPanels.find(x=>x[0]===k)[1]}</label><div class="actions">${btn('↑','dashboard-move',`data-key="${k}" data-delta="-1" aria-label="Mover ${dashboardPanels.find(x=>x[0]===k)[1]} para cima"`,'quiet small')}${btn('↓','dashboard-move',`data-key="${k}" data-delta="1" aria-label="Mover ${dashboardPanels.find(x=>x[0]===k)[1]} para baixo"`,'quiet small')}</div></div>`).join('')}</div>${btn('Restaurar disposição','dashboard-reset','','secondary small')}`)}
document.addEventListener('change',event=>{if(event.target.dataset.dashboardVisible){const layout=writeStudio().layout,k=event.target.dataset.dashboardVisible;layout.hidden=event.target.checked?layout.hidden.filter(v=>v!==k):[...new Set([...layout.hidden,k])];persist();render()}});
function viewSubjectsHub(){return heading('Seu aprendizado tem um lugar.','Abra um assunto para conectar materiais, prática, erros e conversas.',btn('Voltar ao edital','navigate','data-route="edital"'))+`<div class="grid three">${allTopics().filter(x=>!x.s.archived).map(x=>`<section class="panel">${tag(x.s.name)}<h2 style="margin-top:12px">${esc(x.t.name)}</h2><p class="form-help">${esc(reason(x.s,x.t))}</p>${btn('Abrir assunto','topic-hub',`data-sid="${x.s.id}" data-tid="${x.t.id}"`,'secondary small')}</section>`).join('')}</div>`}
function topicHub(){const s=subject(studySubjectId),t=topic(studySubjectId,studyTopicId);if(!s||!t)return viewSubjectsHub();const e=exam(),st=topicStats(s.id,t.id),notes=studio().notes[t.id]||t.notes||'',matches=c=>c.subjectId===s.id&&c.topicId===t.id;return heading(esc(t.name),esc(s.name)+' · '+esc(reason(s,t)),btn('Estudar','start-focus',`data-sid="${s.id}" data-tid="${t.id}"`,'primary')+btn('Editar assunto','topic-edit',`data-sid="${s.id}" data-tid="${t.id}"`))+`<div class="metrics">${metric('Tempo registrado',minutesLabel(st.m||0))}${metric('Questões',st.q)}${metric('Acerto',st.accuracy===null?'Sem dados':st.accuracy+'%')}${metric('Próxima revisão',t.nextReview?dateLabel(t.nextReview):'Não agendada')}</div><div class="grid two"><section class="panel">${panelHead('Suas palavras','Notas locais, enviadas à IA apenas quando selecionadas.')}<form id="topic-notes"><label>Anotações<textarea name="notes" maxlength="12000" rows="8">${esc(notes)}</textarea></label><div class="actions">${btn('Criar cartão desta nota','note-card','','secondary small')}<button class="primary small">Salvar notas</button></div></form></section><section class="panel">${panelHead('Materiais deste assunto')}${e.resources.filter(matches).map(r=>`<div class="insight"><h3>${esc(r.title)}</h3><p>${esc(r.notes)}</p>${safeURL(r.url)?`<a href="${esc(safeURL(r.url))}" target="_blank" rel="noopener noreferrer">Abrir material</a>`:''}</div>`).join('')||'<p>Nenhum material vinculado.</p>'}${btn('Adicionar material','resource-new','','secondary small')}</section><section class="panel">${panelHead('Erros e cartões')}<p>${e.mistakes.filter(m=>matches(m)&&!m.resolved).length} dificuldades em aberto · ${e.cards.filter(matches).length} cartões.</p>${e.mistakes.filter(matches).slice(0,8).map(m=>`<div class="insight"><h3>${esc(m.title)}</h3>${btn('Retomar dificuldade','mistake-edit',`data-id="${m.id}"`,'quiet small')}</div>`).join('')}${btn('Praticar questões do assunto','bank-topic',`data-sid="${s.id}" data-tid="${t.id}"`,'secondary small')}</section><section class="panel">${panelHead('Conversas relacionadas')}${(db.aiChats||[]).filter(c=>c.examId===e.id&&normalizeSearch(c.title+' '+c.messages.filter(m=>m.role==='user').map(m=>m.content).join(' ')).includes(normalizeSearch(t.name))).slice(0,8).map(c=>btn(esc(c.title),'search-chat',`data-id="${c.id}"`,'secondary small')).join('')||'<p>Nenhuma conversa menciona este assunto ainda.</p>'}${btn('Conversar sobre o assunto','topic-tutor','','quiet small')}</section><section class="panel">${panelHead('Últimos estudos')}${historyList(e.sessions.filter(matches).slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,10))}</section></div>`}
function renderStudyRoute(){return studyTopicId?topicHub():viewSubjectsHub()}
routes.push(['assuntos','Meus assuntos']);sidebarGroups[0][1].push('assuntos');sidebarPaths.assuntos='<path d="M4 4h6a3 3 0 0 1 3 3v14a4 4 0 0 0-4-2H4zM13 7a3 3 0 0 1 3-3h5v15h-4a4 4 0 0 0-4 2"/>';
const renderBeforeStudy=render;render=function(){renderBeforeStudy();document.body.classList.toggle('concentration',concentration&&route==='foco');if(route==='foco'&&exam()&&!$('#focus-workspace'))$('#content').insertAdjacentHTML('beforeend',focusWorkspace())};
function focusWorkspace(){const sid=db.timer?.subjectId||exam().subjects.find(s=>!s.archived)?.id,tid=db.timer?.topicId||null,s=subject(sid),t=topic(sid,tid),key=tid||sid;return `<section class="panel focus-workspace" id="focus-workspace">${panelHead('Seu espaço de concentração','Material e anotações ao lado do foco.',btn(concentration?'Sair da concentração':'Modo concentração','concentration-toggle','','secondary small'))}${s?`<p>${esc(t?.name||s.name)}</p><div class="actions">${exam().resources.filter(r=>r.subjectId===sid&&(!tid||r.topicId===tid)).slice(0,5).map(r=>btn(esc(r.title),'resource-edit',`data-id="${r.id}"`,'quiet small')).join('')}</div><form id="focus-notes" data-key="${esc(key)}"><label>Ideias para guardar<textarea name="notes" maxlength="12000" rows="5">${esc(studio().notes[key]||'')}</textarea></label><button class="secondary small">Salvar anotação</button></form>`:'<p>Escolha uma matéria e comece uma sessão para usar este espaço.</p>'}</section>`}
document.addEventListener('submit',event=>{if(!['topic-notes','focus-notes'].includes(event.target.id))return;event.preventDefault();const key=event.target.id==='topic-notes'?studyTopicId:event.target.dataset.key;if(!key)return;const value=String(new FormData(event.target).get('notes')||'').slice(0,12000);const d=writeStudio();const old=d.notes[key];d.notes[key]=value;try{studioRoom();commit('Anotação salva neste aparelho.')}catch(e){if(old===undefined)delete d.notes[key];else d.notes[key]=old;toast(e.message)}});
function prepareRecovery(){
 const e=exam(),late=e.plans.filter(p=>p.status==='planned'&&p.date<today());if(!late.length)return toast('Não há atividades atrasadas para reorganizar.');
 const slots=generatePlan(e,today(),7,e.blockMinutes,e.availability,false);recoveryPreview=late.slice(0,slots.length).map((p,i)=>({oldId:p.id,oldDate:p.date,...slots[i],subjectId:p.subjectId,topicId:p.topicId,type:p.type,reason:'Retomada de '+dateLabel(p.date)}));
 modal('Retome sem sobrecarregar','Revise os horários livres encontrados para os próximos 7 dias.',`<p>${recoveryPreview.length} de ${late.length} atividades cabem nos horários disponíveis. As demais ficam pendentes.</p><div class="preview-list">${recoveryPreview.map(p=>`<div class="row"><div class="row-main"><h3>${esc(topicName(p.subjectId,p.topicId))}</h3><p>${dateLabel(p.date)} · ${p.start}–${p.end}</p></div></div>`).join('')||'<p>Nenhum horário livre. Ajuste sua disponibilidade antes de tentar novamente.</p>'}</div>`,'Aplicar retomada',()=>{if(!recoveryPreview.length)throw Error('Não há horários para aplicar.');snapshot();for(const p of recoveryPreview){const old=e.plans.find(x=>x.id===p.oldId&&x.status==='planned');if(!old)continue;old.status='skipped';const {oldId,oldDate,...newPlan}=p;e.plans.push(newPlan)}recoveryPreview=[];closeModal();commit('Atividades redistribuídas. Você pode desfazer.',true)});
}
const planBeforeStudy=viewPersonalPlan;viewPersonalPlan=function(){return `<div class="actions study-toolbar">${btn('Reorganizar atrasadas','plan-recover','','secondary small')}</div>`+planBeforeStudy()};
const reviewsBeforeStudy=viewReviews;viewReviews=function(){return `<div class="actions study-toolbar">${btn('Minha fila de estudo','queue-open','','secondary small')}</div>`+reviewsBeforeStudy()};
function reviewInterval(t,rating,date){const logs=studio().reviewLog.filter(r=>r.topicId===t.id).slice(-5),last=logs.at(-1),st=topicStats(studySubjectId||exam().subjects.find(s=>s.topics.some(x=>x.id===t.id))?.id,t.id,30);let interval=rating==='again'?1:rating==='hard'?3:Math.min(180,Math.max(4,Math.round((last?.interval||3)*(rating==='easy'?2.4:1.8))));if(st.q>=5&&st.accuracy<exam().targetAccuracy&&rating!=='again')interval=Math.min(interval,7);if(logs.filter(r=>r.rating==='again').length>=2)interval=Math.min(interval,3);return interval}
// The existing session form owns validation, record creation and timer completion.
const sessionBeforeStudy=sessionForm;sessionForm=function(options={}){sessionBeforeStudy(options);const form=$('#modal-form');if(!form)return;const save=form.onsubmit;
 if(options.review){form.insertAdjacentHTML('beforeend','<p class="form-help">O intervalo considera sua lembrança e o desempenho recente; ele não representa uma previsão exata de retenção.</p>')}
 if(options.timer&&!options.existing)form.querySelector('[name="notes"]').closest('label').insertAdjacentHTML('afterend','<label class="full">O que precisa retomar?<textarea name="nextStep" maxlength="3000" rows="2"></textarea></label><label class="full">Transformar em próximo passo<select name="followup"><option value="none">Somente registrar</option><option value="card">Abrir criação de cartão</option><option value="review">Agendar revisão do assunto amanhã</option></select></label>');
 form.onsubmit=event=>{const data=new FormData(form),notes=form.elements.notes,originalNotes=notes.value,extra=String(data.get('nextStep')||'').trim();if(extra)notes.value=notes.value+'\nRetomar: '+extra;const before=exam()?.sessions.length||0;save(event);if($('#modal').open||!exam()||exam().sessions.length===before){notes.value=originalNotes;return}const record=exam().sessions.at(-1),t=topic(record.subjectId,record.topicId);
  if(options.review&&t){const rating=String(data.get('reviewRating')),interval=reviewInterval(t,rating,record.date);t.nextReview=addDays(record.date,interval);const d=writeStudio();d.reviewLog.push({topicId:t.id,date:record.date,rating,interval});d.reviewLog=d.reviewLog.slice(-1000);persist();render()}
  if(data.get('followup')==='review'&&t){t.nextReview=addDays(record.date,1);persist();render()}
  if(data.get('followup')==='card')openCard(null,{subjectId:record.subjectId,topicId:record.topicId,front:extra||'O que aprendi nesta sessão?',back:record.notes});
 };
};
Object.assign(actions,{
 'subjects-hub':()=>{studyTopicId=null;go('assuntos')},'topic-hub':b=>{studySubjectId=b.dataset.sid;studyTopicId=b.dataset.tid;go('assuntos')},
 'dashboard-edit':customizeDashboard,'dashboard-reset':()=>{writeStudio().layout={order:dashboardPanels.map(x=>x[0]),hidden:[]};persist();render();customizeDashboard()},
 'dashboard-move':b=>{const order=writeStudio().layout.order,i=order.indexOf(b.dataset.key),next=Math.max(0,Math.min(order.length-1,i+Number(b.dataset.delta)));[order[i],order[next]]=[order[next],order[i]];persist();render();customizeDashboard()},
 'queue-refresh':()=>render(),'queue-open':()=>modal('Sua fila de estudo','Escolha o tempo e pratique um passo de cada vez.',queuePanel()),
 'queue-start':b=>{const q=learningQueue()[Number(b.dataset.index)];if(!q)return;closeModal();if(q.kind==='card'){reviewCardId=q.itemId;cardMode='review';cardAnswer=false;go('cartoes')}else{if(db.timer){go('foco');return toast('Sua sessão atual foi preservada.')}focusMode='countdown';startFocus(q.sid,q.tid);db.timer.duration=q.minutes*60;if(db.timer.alarm.atSeconds>=db.timer.duration)db.timer.alarm.atSeconds=0;persist();render()}},
 'plan-recover':prepareRecovery,'concentration-toggle':()=>{concentration=!concentration;render()},
 'note-card':()=>openCard(null,{subjectId:studySubjectId,topicId:studyTopicId,front:topicName(studySubjectId,studyTopicId),back:$('#topic-notes textarea')?.value||''}),
 'topic-tutor':()=>{if(aiBusy)return toast('Aguarde ou cancele o pedido atual.');aiChatId=null;aiResult=null;aiContent='Ajude-me a entender '+topicName(studySubjectId,studyTopicId)+'.\nMaterial de referência:\n'+(studio().notes[studyTopicId]||topic(studySubjectId,studyTopicId)?.notes||'Ainda não forneci uma referência. Pergunte qual material posso trazer.');aiMode='explain';go('ia')}
});
const rateBeforeStudy=actions['card-rate'];
actions['card-rate']=b=>{const c=exam()?.cards.find(c=>c.id===b.dataset.id);if(!c)return;const oldInterval=c.interval,rating=b.dataset.value;const history=studio().reviewLog.filter(row=>row.cardId===c.id).slice(-5),performance=c.topicId?topicStats(c.subjectId,c.topicId,30):null;let interval=rating==='again'?1:rating==='hard'?3:Math.min(180,Math.max(rating==='easy'?7:4,Math.round((oldInterval||3)*(rating==='easy'?2.4:1.8))));if(performance?.q>=5&&performance.accuracy<exam().targetAccuracy)interval=Math.min(interval,7);if(history.filter(row=>row.rating==='again').length>=2)interval=Math.min(interval,3);rateBeforeStudy(b);c.interval=interval;c.due=addDays(today(),interval);const d=writeStudio();d.reviewLog.push({topicId:c.topicId||'card:'+c.id,cardId:c.id,date:today(),rating,interval});d.reviewLog=d.reviewLog.slice(-1000);persist();render();toast('Próxima revisão em '+interval+' dias, conforme sua lembrança e prática recente.')};
