let focusAlarmSettings={sound:true,atMinutes:0},timerAudio=null,timerAlert='',timerPip=null,timerDockKey='',timerPipKey='',timerDragFrame=0;
function timerOptions(t){const alarm=t?.alarm||focusAlarmSettings;return `<div class="timer-options"><div class="timer-option-title"><h3>Um lembrete no momento certo.</h3><button type="button" class="quiet small" data-action="timer-sound-test">Testar som</button></div><label class="checkbox-label"><input id="timer-sound" type="checkbox" ${alarm.sound?'checked':''}>Som ao concluir e no lembrete</label><label>Lembrete após quantos minutos de estudo?<input id="timer-reminder" type="number" min="0" max="1440" step="1" value="${t?Math.round((alarm.atSeconds||0)/60):alarm.atMinutes||0}" inputmode="numeric"></label><p class="form-help">Use 0 para desativar. No bloco de foco, escolha um tempo menor que a duração total.</p><div class="timer-floating-actions">${t?btn('Abrir minipainel','timer-dock-open','','secondary small')+btn('Flutuar sobre outras janelas','timer-pip','','secondary small'):''}</div><p class="form-help">A janela sobre outros sites depende do suporte do navegador. Mantenha o Norte aberto. Aparelhos em suspensão podem atrasar os avisos.</p><p id="timer-audio-status" class="form-help" role="status"></p></div>`}
function timerUnlockAudio(){try{if(!timerAudio){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return Promise.resolve(false);timerAudio=new Audio()}return timerAudio.resume().then(()=>timerAudio.state==='running').catch(()=>false)}catch{return Promise.resolve(false)}}
function timerPlaySound(finish=false){if(tour||!timerAudio||timerAudio.state!=='running')return false;try{const now=timerAudio.currentTime;[finish?523:659,finish?659:784,finish?784:659].forEach((hz,i)=>{const oscillator=timerAudio.createOscillator(),gain=timerAudio.createGain(),start=now+i*.22;oscillator.type='sine';oscillator.frequency.value=hz;gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(.14,start+.025);gain.gain.exponentialRampToValueAtTime(.001,start+.18);oscillator.connect(gain);gain.connect(timerAudio.destination);oscillator.start(start);oscillator.stop(start+.2)});return true}catch{return false}}
function timerFireAlert(message,finish=false){if(tour)return;timerAlert=message;const sounded=db.timer?.alarm?.sound&&timerPlaySound(finish);toast(message+(db.timer?.alarm?.sound&&!sounded?' Ative o som com “Testar som”.':''));if($('#timer-audio-status'))$('#timer-audio-status').textContent=sounded?'Alarme reproduzido.':message;}
function startFocus(sid,tid,pid){if(db.timer){go('foco');toast('Você já tem uma sessão aberta.');return}const s=subject(sid);if(!s){go('foco');return}const p=exam().plans.find(p=>p.id===pid),duration=(p?timeMin(p.end)-timeMin(p.start):exam().blockMinutes)*60;timerAlert='';db.timer={examId:exam().id,subjectId:sid,topicId:tid||null,planId:pid||null,date:today(),mode:focusMode,duration,elapsed:0,startedAt:Date.now(),running:true,notified:false,alarm:{sound:focusAlarmSettings.sound,atSeconds:focusMode==='countdown'&&focusAlarmSettings.atMinutes*60>=duration?0:focusAlarmSettings.atMinutes*60,fired:false},dockVisible:true,dockOnFocus:false};timerUnlockAudio();persist();go('foco')}
function timerSurface(t,pip=false){const e=db.exams.find(e=>e.id===t.examId),s=e?.subjects.find(s=>s.id===t.subjectId),topic=s?.topics.find(x=>x.id===t.topicId),finished=t.mode==='countdown'&&t.notified;return `<section class="focus-mini ${finished?'is-finished':''}" aria-label="Cronômetro flutuante"><header class="focus-mini-header"><span ${pip?'':'data-timer-drag'} class="focus-mini-grip">NORTE · FOCO</span><button class="quiet small" data-action="${pip?'timer-pip-close':'timer-dock-close'}" aria-label="Fechar ${pip?'janela':'minipainel'}">×</button></header><h2>${esc(topic?.name||s?.name||'Sessão de estudo')}</h2><p>${esc(s?.name||'Seu tempo de foco')}</p><strong class="focus-mini-count" data-timer-count>00:00</strong><span class="focus-mini-status" data-timer-status></span><div class="focus-mini-track"><span data-timer-progress></span></div>${timerAlert?`<div class="focus-mini-alert" role="status">${esc(timerAlert)}${btn('Entendi','timer-alert-dismiss','','quiet small')}</div>`:''}<div class="focus-mini-controls">${btn(finished?'Concluído':t.running?'Pausar':'Continuar','timer-toggle',finished?'disabled':'','primary small')}${btn('Registrar','timer-finish','','secondary small')}</div><div class="focus-mini-footer">${pip?'':btn('Voltar ao foco','navigate','data-route="foco"','quiet small')+btn('Janela flutuante','timer-pip','','quiet small')}</div></section>`}
function updateTimer(){const t=db.timer,dock=$('#timer-dock');if(!dock)return;if(!t){dock.hidden=true;timerDockKey='';timerAlert='';if(timerPip&&!timerPip.closed)timerPip.close();timerPip=null;return}let elapsed=timerElapsed(t);const alarm=t.alarm;
 if(t.mode==='countdown'&&elapsed>=t.duration&&t.running){t.elapsed=t.duration;t.running=false;elapsed=t.duration;const first=!t.notified;t.notified=true;if(alarm&&alarm.atSeconds>0&&elapsed>=alarm.atSeconds)alarm.fired=true;persist();if(first)timerFireAlert('Bloco concluído. Hora de uma pausa.',true);if(route==='foco'){const button=$('[data-action="timer-toggle"]');if(button){button.textContent='Concluído';button.disabled=true}}}
 else if(t.running&&alarm&&alarm.atSeconds>0&&!alarm.fired&&elapsed>=alarm.atSeconds){alarm.fired=true;persist();timerFireAlert('Lembrete: '+Math.round(alarm.atSeconds/60)+' minutos de estudo concluídos.')}
 const seconds=t.mode==='free'?elapsed:Math.max(0,t.duration-elapsed),status=t.running?'Sessão em andamento':t.notified?'Bloco concluído. Hora de uma pausa.':'Sessão pausada';if($('#timer-count'))$('#timer-count').textContent=clockLabel(seconds);if($('#timer-status'))$('#timer-status').textContent=status;if(route==='foco'&&t.notified&&t.mode==='countdown'){const b=$('[data-action="timer-toggle"]');if(b){b.textContent='Concluído';b.disabled=true}}
 if(timerPip?.closed)timerPip=null;dock.hidden=t.dockVisible===false||(route==='foco'&&!t.dockOnFocus)||!!timerPip;const key=[t.examId,t.startedAt,t.running,t.notified,t.mode,db.theme,timerAlert].join('|');
 if(dock.hidden){dock.innerHTML='';timerDockKey=''}
 if(!dock.hidden&&key!==timerDockKey){dock.innerHTML=timerSurface(t);timerDockKey=key}
 if(timerPip&&key!==timerPipKey){timerPip.document.documentElement.dataset.theme=db.theme;timerPip.document.body.innerHTML=timerSurface(t,true);timerPipKey=key}
 for(const doc of [document,...(timerPip?[timerPip.document]:[])]){doc.querySelectorAll('[data-timer-count]').forEach(el=>el.textContent=clockLabel(seconds));doc.querySelectorAll('[data-timer-status]').forEach(el=>el.textContent=status);doc.querySelectorAll('[data-timer-progress]').forEach(el=>el.style.width=(t.mode==='free'?0:Math.min(100,elapsed/t.duration*100))+'%')}
}
async function openTimerPip(){if(tour)return toast('A janela externa fica desativada durante o tutorial.');if(!db.timer)return toast('Comece uma sessão primeiro.');timerUnlockAudio();if(timerPip&&!timerPip.closed){timerPip.focus();return}if(!window.documentPictureInPicture?.requestWindow){db.timer.dockVisible=true;db.timer.dockOnFocus=true;commit();return toast('Este navegador não oferece uma janela sempre visível. Use o minipainel no Norte.')}
 try{const popup=await window.documentPictureInPicture.requestWindow({width:360,height:390});if(!db.timer){popup.close();return}timerPip=popup;timerPipKey='';popup.document.title='Norte · Cronômetro';const style=popup.document.createElement('style');style.textContent=$('style').textContent+'\nbody{margin:0;padding:16px;background:var(--bg)}.focus-mini{width:100%;box-shadow:none}.focus-mini-header .focus-mini-grip{cursor:default}';popup.document.head.append(style);popup.document.body.addEventListener('click',event=>{const b=event.target.closest('[data-action]');if(!b||b.disabled)return;event.preventDefault();if(b.dataset.action==='timer-finish'){popup.close();go('foco');window.focus()}actions[b.dataset.action]?.(b);updateTimer()});popup.addEventListener('pagehide',()=>{if(timerPip===popup){timerPip=null;timerPipKey='';timerDockKey='';updateTimer()}});updateTimer()}catch{toast('A janela não foi aberta. Tente pelo botão novamente ou use o minipainel.')}}
Object.assign(actions,{
 'timer-start':()=>{const sid=$('#focus-subject')?.value,tid=$('#focus-topic')?.value,duration=Number($('#focus-duration')?.value||30)*60;if(!sid)return toast('Adicione uma matéria primeiro.');if(focusMode==='countdown'&&focusAlarmSettings.atMinutes*60>=duration)return toast('Escolha um lembrete menor que a duração do bloco, ou use 0.');startFocus(sid,tid);db.timer.duration=duration;db.timer.alarm.atSeconds=focusAlarmSettings.atMinutes*60;persist();updateTimer()},
 'timer-toggle':()=>{timerUnlockAudio();updateTimer();toggleTimer()},
 'timer-finish':()=>{updateTimer();finishTimer()},
 'timer-sound-test':async()=>{const enabled=await timerUnlockAudio(),ok=enabled&&timerPlaySound();if($('#timer-audio-status'))$('#timer-audio-status').textContent=ok?'Som ativado. Confira o volume do aparelho.':'O navegador não liberou o som. Tente novamente.';toast(ok?'Som de teste reproduzido.':'Som indisponível neste navegador.')},
 'timer-dock-open':()=>{if(!db.timer)return;db.timer.dockVisible=true;db.timer.dockOnFocus=true;timerDockKey='';commit()},
 'timer-dock-close':()=>{if(!db.timer)return;db.timer.dockVisible=false;commit()},
 'timer-pip':openTimerPip,'timer-pip-close':()=>timerPip?.close(),
 'timer-alert-dismiss':()=>{timerAlert='';timerDockKey='';timerPipKey='';updateTimer()}
});
document.addEventListener('change',event=>{const el=event.target;if(!['timer-sound','timer-reminder'].includes(el.id))return;const t=db.timer;if(el.id==='timer-sound'){focusAlarmSettings.sound=el.checked;if(t){t.alarm??={atSeconds:0,fired:false};t.alarm.sound=el.checked}if(el.checked)timerUnlockAudio()}else{const minutes=Number(el.value);if(!Number.isInteger(minutes)||minutes<0||minutes>1440||t?.mode==='countdown'&&minutes*60>=t.duration){el.value=t?Math.round((t.alarm?.atSeconds||0)/60):focusAlarmSettings.atMinutes;return toast('Use um número inteiro de 0 a 1440, menor que a duração do bloco.')}focusAlarmSettings.atMinutes=minutes;if(t){t.alarm??={sound:focusAlarmSettings.sound};t.alarm.atSeconds=minutes*60;t.alarm.fired=minutes>0&&timerElapsed(t)>=minutes*60;if(t.alarm.fired)toast('Esse tempo já passou. O lembrete valerá para o próximo bloco.')}}if(t)persist();updateTimer()});
document.addEventListener('visibilitychange',()=>{if(!document.hidden)updateTimer()});window.addEventListener('pagehide',()=>{if(timerPip&&!timerPip.closed)timerPip.close()});
// Drag tracks the pointer; release settles inside the viewport with carried velocity.
document.addEventListener('pointerdown',event=>{const handle=event.target.closest('[data-timer-drag]');if(!handle||event.button!==0)return;const dock=$('#timer-dock'),rect=dock.getBoundingClientRect();cancelAnimationFrame(timerDragFrame);handle.setPointerCapture(event.pointerId);event.preventDefault();let x=rect.left,y=rect.top,vx=0,vy=0,last=performance.now(),px=event.clientX,py=event.clientY;Object.assign(dock.style,{left:x+'px',top:y+'px',right:'auto',bottom:'auto'});const move=e=>{const now=performance.now(),dt=Math.max(1,now-last);vx=(e.clientX-px)/dt*1000;vy=(e.clientY-py)/dt*1000;x+=e.clientX-px;y+=e.clientY-py;px=e.clientX;py=e.clientY;last=now;dock.style.left=x+'px';dock.style.top=y+'px'};const release=()=>{handle.removeEventListener('pointermove',move);handle.removeEventListener('pointerup',release);handle.removeEventListener('pointercancel',release);const tx=Math.max(8,Math.min(innerWidth-dock.offsetWidth-8,x+vx*.12)),ty=Math.max(8,Math.min(innerHeight-dock.offsetHeight-8,y+vy*.12));if(matchMedia('(prefers-reduced-motion: reduce)').matches){dock.style.left=tx+'px';dock.style.top=ty+'px';return}let time=performance.now();const step=now=>{const dt=Math.min(.032,(now-time)/1000);time=now;vx+=(260*(tx-x)-32*vx)*dt;vy+=(260*(ty-y)-32*vy)*dt;x+=vx*dt;y+=vy*dt;dock.style.left=x+'px';dock.style.top=y+'px';if(Math.abs(tx-x)+Math.abs(ty-y)+Math.abs(vx)+Math.abs(vy)>.5)timerDragFrame=requestAnimationFrame(step);else{dock.style.left=tx+'px';dock.style.top=ty+'px'}};timerDragFrame=requestAnimationFrame(step)};handle.addEventListener('pointermove',move);handle.addEventListener('pointerup',release);handle.addEventListener('pointercancel',release)});
window.addEventListener('resize',()=>{const dock=$('#timer-dock');if(!dock||dock.hidden||!dock.style.left)return;cancelAnimationFrame(timerDragFrame);const rect=dock.getBoundingClientRect();dock.style.left=Math.max(8,Math.min(innerWidth-dock.offsetWidth-8,rect.left))+'px';dock.style.top=Math.max(8,Math.min(innerHeight-dock.offsetHeight-8,rect.top))+'px'});
