/* Explicit, bounded tutor requests. Cached responses never require an API call. */
let tutorTool='explain',tutorSource='',tutorRemaining=null,tutorCacheHit=false,tutorHintsShown=0,tutorMissionDone=[];
const tutorTools=[
 ['explain','Explicação guiada','Conceito, raciocínio, exemplo e recuperação.'],
 ['diagnosis','Diagnóstico de erros','Analise um lote de dificuldades registradas.'],
 ['feedback','Corrigir minha explicação','Compare suas palavras ao material escolhido.'],
 ['hints','Pistas graduais','Receba três pistas e revele uma por vez.'],
 ['mission','Missão de estudo','Uma sequência curta para executar sem novas chamadas.'],
 ['notes','Organizar anotações','Transforme notas em conceitos e perguntas de revisão.'],
 ['compare','Comparar conceitos','Distinga ideias que costumam se confundir.'],
 ['cardcheck','Revisar meus cartões','Revise clareza e tamanho de um pequeno lote.'],
 ['weekly','Orientação semanal','Dois ou três ajustes baseados em registros reais.']
];
const validateBeforeTutor=aiValidResult;
aiValidResult=function(mode,data,count=3){if(!validateBeforeTutor(mode,data,count))return false;if(mode==='explain'){if(data.basis!==undefined&&!['source','general','insufficient'].includes(data.basis))return false;if(data.quote!==undefined&&(typeof data.quote!=='string'||data.quote.length>600))return false;for(const key of ['hints','steps'])if(data[key]!==undefined&&(!Array.isArray(data[key])||data[key].length>(key==='hints'?3:5)||data[key].some(v=>typeof v!=='string'||!v.trim()||v.length>2000)))return false;if(data.completedSteps!==undefined&&(!Array.isArray(data.completedSteps)||data.completedSteps.some(i=>!Number.isInteger(i)||i<0||i>4)))return false}else if(mode==='quiz'){if(data.questions.some(q=>new Set(q.options.map(v=>v.trim().toLocaleLowerCase())).size!==4||q.choice!==undefined&&(!Number.isInteger(q.choice)||q.choice<0||q.choice>3)||q.revealed!==undefined&&typeof q.revealed!=='boolean'))return false}return true};
function tutorSourceText(){const r=exam()?.resources.find(r=>r.id===tutorSource);return r?.notes?.trim()?r.notes.slice(0,8000):''}
function tutorPanel(){if(!exam())return '';const cache=studio().cache;return `<section class="panel tutor-workbench" id="tutor-workbench">${panelHead('Mais maneiras de aprender','Cada envio gera um resultado que você pode guardar e reutilizar.')}<div class="tutor-tools">${tutorTools.map(([key,label,sub])=>`<button data-action="tutor-tool" data-tool="${key}" aria-pressed="${tutorTool===key}" ${aiBusy?'disabled':''}><strong>${esc(label)}</strong><small>${esc(sub)}</small></button>`).join('')}</div><label class="tutor-source-label">Material de referência (opcional)<select id="tutor-source" ${aiBusy?'disabled':''}><option value="">Sem material selecionado</option>${exam().resources.filter(r=>r.notes.trim()).map(r=>`<option value="${r.id}" ${r.id===tutorSource?'selected':''}>${esc(r.title)}</option>`).join('')}</select></label>${tutorSourceText()?`<details class="tutor-source-preview"><summary>Conferir o trecho que será enviado</summary><pre>${esc(tutorSourceText())}</pre></details>`:'<p class="form-help">Selecionar um link não lê a página externa. Só as notas do material escolhido serão enviadas.</p>'}<p class="form-help">${tutorRemaining===null?'Há um orçamento compartilhado para todos os visitantes.':tutorRemaining+' pedidos restantes no orçamento compartilhado, conforme a última resposta.'} Reabrir respostas salvas não consome um pedido.</p><details id="tutor-saved"><summary>Respostas reutilizáveis (${cache.length})</summary>${cache.slice().reverse().map(row=>`<div class="row"><div class="row-main"><h3>${esc(row.label)}</h3><small>${new Date(row.date).toLocaleDateString('pt-BR')}</small></div>${btn('Reabrir','tutor-cache-open',`data-key="${esc(row.key)}"`,'quiet small')}${btn('Excluir','tutor-cache-delete',`data-key="${esc(row.key)}"`,'quiet small')}</div>`).join('')||'<p>Resultados novos ficam aqui. Não são compartilhados com outros usuários.</p>'}</details></section>`}
const aiViewBeforeTutor=viewAI;
viewAI=function(){return aiViewBeforeTutor()+tutorPanel()};
function tutorSeed(tool){
 const e=exam();if(!e)return '';
 if(tool==='diagnosis')return 'Analise estas dificuldades sem inventar causas. Aponte padrões possíveis e como verificá-los:\n'+e.mistakes.filter(m=>!m.resolved).slice(0,8).map(m=>m.title+'\nMinha anotação: '+m.explanation.slice(0,450)).join('\n\n');
 if(tool==='cardcheck')return 'Revise a clareza destes cartões. Proponha perguntas específicas, uma ideia por cartão, e diga o que precisa conferir na fonte:\n'+e.cards.filter(c=>!c.suspended).slice(0,6).map(c=>'Pergunta: '+c.front.slice(0,400)+'\nResposta: '+c.back.slice(0,500)).join('\n\n');
 if(tool==='weekly'){const s=stats(periodSessions(7));return 'Sugira dois ou três ajustes possíveis para a próxima semana. Não invente resultados nem altere meu plano:\n'+JSON.stringify({minutes:s.m,questions:s.q,correct:s.c,accuracy:s.accuracy,dailyMinutes:e.dailyMinutes,weeklyMinutes:e.weeklyMinutes,latePlans:e.plans.filter(p=>p.date<today()&&p.status==='planned').length,dueReviews:dueTopics().length})}
 return {feedback:'Minha explicação com minhas palavras:\n\nCompare com o material selecionado e mostre o que compreendi, o que falta e como corrigir.',hints:'Questão que quero resolver sem ver o gabarito:\n\nPrepare três pistas progressivas sem entregar diretamente a resposta.',mission:'Crie uma missão curta de estudo sobre este assunto:\n\nQuero tentar lembrar, praticar e conferir.',notes:'Organize estas anotações sem adicionar fatos:\n\n',compare:'Quero comparar estes dois conceitos:\nConceito 1: \nConceito 2: \nDê exemplos e explique os limites da comparação.',explain:''}[tool]||'';
}
document.addEventListener('change',event=>{if(event.target.id==='tutor-source'){tutorSource=event.target.value;aiCleanupWidget();tutorCacheHit=false;aiContent=$('#ai-content')?.value||aiContent;render()}});
function tutorText(text){return String(text||'').split(/\n\s*\n/).map(part=>{const lines=part.split('\n'),first=lines[0].replace(/^#{1,4}\s*/, '').replace(/^\*\*(.*?)\*\*:?$/,'$1');if(/^#{1,4}\s|^\*\*[^*]+\*\*/.test(lines[0]))return '<section class="tutor-section"><h3>'+esc(first)+'</h3><p>'+esc(lines.slice(1).join('\n'))+'</p></section>';return '<p>'+esc(part)+'</p>'}).join('')}
function tutorAnswer(result){const basis={source:'Apoiada no material selecionado',general:'Explicação geral · confira no seu material',insufficient:'Material insuficiente · traga uma referência'};return `<div class="tutor-answer"><span class="tag ${result.basis==='insufficient'?'amber':'blue'}">${esc(basis[result.basis]||'Resposta de estudo · confira a fonte')}</span>${tutorCacheHit?'<p class="form-help">Resposta reutilizada neste aparelho. Nenhum novo pedido foi feito.</p>':''}<div class="tutor-prose">${tutorText(result.explanation)}</div>${result.quote?`<details class="tutor-evidence"><summary>Trecho de apoio conferido</summary><blockquote>${esc(result.quote)}</blockquote></details>`:''}${result.hints?.length?`<section class="tutor-hints"><h3>Pense um passo de cada vez.</h3>${result.hints.slice(0,tutorHintsShown).map((hint,i)=>`<div class="note"><strong>Pista ${i+1}</strong><p>${esc(hint)}</p></div>`).join('')}${btn(tutorHintsShown?'Revelar próxima pista':'Revelar primeira pista','tutor-hint',tutorHintsShown>=result.hints.length?'disabled':'','secondary small')}<p class="form-help">As pistas já estão salvas. Revelar não chama a IA.</p></section>`:''}${result.steps?.length?`<section class="tutor-mission"><h3>Sua missão de estudo</h3>${result.steps.map((step,i)=>`<label class="checkbox-label"><input type="checkbox" data-mission-step="${i}" ${tutorMissionDone.includes(i)?'checked':''}>${esc(step)}</label>`).join('')}<p class="form-help">Marcar passos não registra tempo. Ao terminar, registre a sessão de estudo.</p>${btn('Registrar sessão','session','','secondary small')}</section>`:''}<div class="actions">${btn('Guardar na biblioteca','tutor-save-resource','','secondary small')}${btn('Criar cartão desta explicação','tutor-save-card','','quiet small')}</div></div>`}
const aiOutputBeforeTutor=aiOutput;aiOutput=function(){if(aiResult?.explanation&&!aiBusy&&!aiError)return tutorAnswer(aiResult);return aiOutputBeforeTutor()};
const quizBeforeTutor=aiQuizOutput;aiQuizOutput=function(){let html=quizBeforeTutor();if(aiResult?.questions&&aiResult.questions.every(q=>q.revealed))html+=`<div class="actions tutor-quiz-actions">${btn('Registrar resultado','ai-register-result','','primary small')}${btn('Salvar questões no banco','ai-bank-save','','secondary small')}</div>`;else if(aiResult?.questions)html+=`<div class="actions tutor-quiz-actions">${btn('Salvar questões no banco','ai-bank-save','','secondary small')}</div>`;return html};
function tutorQuizAttempt(){const questions=aiResult?.questions;if(!questions?.every(q=>q.revealed))return toast('Responda todas as questões antes de registrar.');aiResult.trainingId??=id();const chat=aiCurrentChat(),message=chat?.messages.find(m=>m.result===aiResult),resultId=aiResult.trainingId,existing=studio().attempts.find(a=>a.aiMessageId===resultId);if(existing)return registerAttempt(existing);modal('Vincule o treino ao seu estudo','Escolha o assunto e confira o tempo antes de registrar.',`<div class="form-grid">${selection()}<label class="full">Nome<input name="title" value="Treino da NORBIT AI" maxlength="200" required></label><label>Minutos reais<input name="minutes" type="number" min="0" max="1440" value="0" required></label></div>`,'Conferir resultado',d=>{if(!subject(d.subjectId)||d.topicId&&!topic(d.subjectId,d.topicId)||!Number.isInteger(+d.minutes)||!num(d.minutes,0,1440))throw Error('Confira a matéria, o assunto e os minutos.');if(studio().attempts.length>=100)throw Error('Remova um treino antigo antes de continuar.');const result={id:id(),title:d.title.trim(),date:today(),minutes:+d.minutes,aiMessageId:resultId,questions:questions.map(q=>({...clone(q),id:id(),subjectId:d.subjectId,topicId:d.topicId||null,difficulty:aiGeneratedDifficulty,source:'NORBIT AI'})),choices:questions.map(q=>q.choice)};writeStudio().attempts.push(result);persist();closeModal();registerAttempt(result)})}
function saveAIQuestions(){if(!aiResult?.questions)return;if(!exam())return toast('Crie uma preparação para salvar questões.');modal('Guarde este treino','As questões serão salvas no seu banco pessoal. Confira gabaritos e explicações.',`<div class="form-grid">${selection()}</div>`,'Salvar questões',d=>{if(!subject(d.subjectId)||d.topicId&&!topic(d.subjectId,d.topicId))throw Error('Escolha matéria e assunto válidos.');const keys=new Set(studio().bank.map(q=>normalizeSearch(q.prompt).trim())),items=aiResult.questions.filter(q=>!keys.has(normalizeSearch(q.prompt).trim())).map(q=>({...clone(q),id:id(),subjectId:d.subjectId,topicId:d.topicId||null,difficulty:aiGeneratedDifficulty,source:'NORBIT AI'}));if(!items.length)throw Error('Estas questões já estão no banco.');if(studio().bank.length+items.length>500)throw Error('O banco comporta até 500 questões.');snapshot();const storeData=writeStudio(),old=clone(storeData.bank);storeData.bank.push(...items);try{studioRoom()}catch(e){storeData.bank=old;throw e}closeModal();commit('Questões adicionadas ao banco pessoal.',true)})}
function tutorStore(key,mode,result,label){if(!exam()||tour)return;const d=writeStudio();result.cacheKey=key;if(mode==='quiz')result.trainingId??=key;d.cache=d.cache.filter(row=>row.key!==key);d.cache.push({key,mode,result:clone(result),label:String(label).replace(/\s+/g,' ').slice(0,120),date:new Date().toISOString()});d.cache=d.cache.slice(-20);while(JSON.stringify(d).length>1500000&&d.cache.length)d.cache.shift();persist()}
async function tutorKey(input){if(!crypto.subtle)return null;const bytes=new TextEncoder().encode(JSON.stringify(input)),hash=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('')}
// Sending remains behind the same Turnstile and atomic server budget.
const aiSubmitBeforeTutor=aiSubmit;
let tutorPreparing=false;
aiSubmit=async function(form){
 if(tutorPreparing)return;
 if(aiBusy||tour)return aiSubmitBeforeTutor(form);
 const content=form.elements.content.value.trim();if(content.length<(aiCurrentChat()?.messages.length?1:20)||content.length>8000)return aiSubmitBeforeTutor(form);
 const sourceText=tutorSourceText(),history=aiCurrentChat()?aiChatHistoryPayload(aiCurrentChat()):[],context=aiUseContext?aiStudyContext():'';
 tutorPreparing=true;let key;try{key=await tutorKey({mode:aiMode,tool:aiMode==='explain'?tutorTool:'explain',content,sourceText,context,history,count:aiQuestionCount,difficulty:aiDifficulty})}finally{tutorPreparing=false}
 if(!form.isConnected||aiBusy)return;
 const cached=key&&studio().cache.find(row=>row.key===key);
 if(cached){const turn=aiChatBegin(content,aiMode);aiResult=clone(cached.result);aiExamId=exam()?.id||null;aiSubmittedContent=content;aiContent='';aiError='';aiGeneratedDifficulty=aiDifficulty;aiQuizIndex=0;tutorCacheHit=true;tutorHintsShown=0;tutorMissionDone=[];aiChatFinish(turn,aiResult,'');aiCleanupWidget();render();return}
 tutorCacheHit=false;tutorHintsShown=0;tutorMissionDone=[];
 await aiSubmitBeforeTutor(form);
 // If verification is pending, the original flow invokes this function again.
 if(aiResult&&!aiError&&!aiBusy&&!aiAwaitingVerification)tutorStore(key||id(),aiMode,aiResult,content);
};
Object.assign(actions,{
 'tutor-tool':b=>{if(aiBusy)return;aiCleanupWidget();tutorTool=b.dataset.tool;aiMode='explain';aiResult=null;aiChatId=null;aiError='';aiContent=tutorSeed(tutorTool);tutorHintsShown=0;tutorMissionDone=[];render();aiFocusComposer()},
 'tutor-hint':()=>{tutorHintsShown=Math.min((aiResult?.hints||[]).length,tutorHintsShown+1);render();siteMotion.play($('.tutor-hints .note:last-of-type'),[{opacity:.4,transform:'translateY(5px)'},{opacity:1,transform:'translateY(0)'}],{duration:220})},
 'tutor-cache-open':b=>{const row=studio().cache.find(r=>r.key===b.dataset.key);if(!row||aiBusy)return;aiChatId=null;aiMode=row.mode;aiResult=clone(row.result);aiError='';aiExamId=exam().id;aiSubmittedContent=row.label;aiGeneratedDifficulty='medium';aiQuizIndex=0;tutorCacheHit=true;tutorHintsShown=0;tutorMissionDone=clone(aiResult.completedSteps||[]);render()},
 'tutor-cache-delete':b=>{snapshot();writeStudio().cache=studio().cache.filter(row=>row.key!==b.dataset.key);commit('Resposta removida desta lista. Os chats foram preservados.',true)},
 'tutor-save-resource':()=>{if(!aiResult?.explanation)return;openResource();$('#modal [name="title"]').value=(aiSubmittedContent||'Explicação da NORBIT').replace(/\s+/g,' ').slice(0,250);$('#modal [name="notes"]').value=aiResult.explanation},
 'tutor-save-card':()=>{if(aiResult?.explanation)openCard(null,{subjectId:exam().subjects.find(s=>!s.archived)?.id,front:'Como explicar esta ideia com minhas palavras?',back:aiResult.explanation})},
 'ai-register-result':tutorQuizAttempt,'ai-bank-save':saveAIQuestions
});
const tutorRestartBefore=actions['ai-quiz-restart'];actions['ai-quiz-restart']=()=>{if(!aiResult?.questions)return;aiResult.trainingId=id();tutorRestartBefore();persist()};
document.addEventListener('change',event=>{if(event.target.dataset.missionStep!==undefined){const i=Number(event.target.dataset.missionStep);tutorMissionDone=event.target.checked?[...new Set([...tutorMissionDone,i])]:tutorMissionDone.filter(n=>n!==i);if(aiResult){aiResult.completedSteps=clone(tutorMissionDone);const row=studio().cache.find(r=>r.key===aiResult.cacheKey);if(row)row.result.completedSteps=clone(tutorMissionDone);persist()}}});
